<a href="https://colab.research.google.com/github/AI4Finance-Foundation/FinRL-Tutorials/blob/master/2-Advance/FinRL_Ensemble_StockTrading_ICAIF_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Reinforcement Learning for Stock Trading from Scratch: Multiple Stock Trading Using Ensemble Strategy

Tutorials to use OpenAI DRL to trade multiple stocks using ensemble strategy in one Jupyter Notebook | Presented at ICAIF 2020

* This notebook is the reimplementation of our paper: Deep Reinforcement Learning for Automated Stock Trading: An Ensemble Strategy, using FinRL.
* Check out medium blog for detailed explanations: https://medium.com/@ai4finance/deep-reinforcement-learning-for-automated-stock-trading-f1dad0126a02
* Please report any issues to our Github: https://github.com/AI4Finance-LLC/FinRL-Library/issues
* **Pytorch Version** 



# Content

* [1. Problem Definition](#0)
* [2. Getting Started - Load Python packages](#1)
    * [2.1. Install Packages](#1.1)    
    * [2.2. Check Additional Packages](#1.2)
    * [2.3. Import Packages](#1.3)
    * [2.4. Create Folders](#1.4)
* [3. Download Data](#2)
* [4. Preprocess Data](#3)        
    * [4.1. Technical Indicators](#3.1)
    * [4.2. Perform Feature Engineering](#3.2)
* [5.Build Environment](#4)  
    * [5.1. Training & Trade Data Split](#4.1)
    * [5.2. User-defined Environment](#4.2)   
    * [5.3. Initialize Environment](#4.3)    
* [6.Implement DRL Algorithms](#5)  
* [7.Backtesting Performance](#6)  
    * [7.1. BackTestStats](#6.1)
    * [7.2. BackTestPlot](#6.2)   
    * [7.3. Baseline Stats](#6.3)   
    * [7.3. Compare to Stock Market Index](#6.4)             

<a id='0'></a>
# Part 1. Problem Definition

This problem is to design an automated trading solution for single stock trading. We model the stock trading process as a Markov Decision Process (MDP). We then formulate our trading goal as a maximization problem.

The algorithm is trained using Deep Reinforcement Learning (DRL) algorithms and the components of the reinforcement learning environment are:


* Action: The action space describes the allowed actions that the agent interacts with the
environment. Normally, a ∈ A includes three actions: a ∈ {−1, 0, 1}, where −1, 0, 1 represent
selling, holding, and buying one stock. Also, an action can be carried upon multiple shares. We use
an action space {−k, ..., −1, 0, 1, ..., k}, where k denotes the number of shares. For example, "Buy
10 shares of AAPL" or "Sell 10 shares of AAPL" are 10 or −10, respectively

* Reward function: r(s, a, s′) is the incentive mechanism for an agent to learn a better action. The change of the portfolio value when action a is taken at state s and arriving at new state s',  i.e., r(s, a, s′) = v′ − v, where v′ and v represent the portfolio
values at state s′ and s, respectively

* State: The state space describes the observations that the agent receives from the environment. Just as a human trader needs to analyze various information before executing a trade, so
our trading agent observes many different features to better learn in an interactive environment.

* Environment: Dow 30 consituents


The data of the single stock that we will be using for this case study is obtained from Yahoo Finance API. The data contains Open-High-Low-Close price and volume.


<a id='1'></a>
# Part 2. Getting Started- Load Python Packages

<a id='1.1'></a>
## 2.1. Install all the packages through FinRL library


In [ ]:
!pip install stable_baselines3
!pip install yfinance
!pip install tushare
!pip install exchange_calendars
!pip install wrds
!pip install alpaca_trade_api
!pip install stockstats
!pip install pyfolio

In [ ]:
# ## install finrl library
!pip install wrds
!pip install swig
!pip install git+https://github.com/AI4Finance-Foundation/FinRL.git


<a id='1.2'></a>
## 2.2. Check if the additional packages needed are present, if not install them. 
* Yahoo Finance API
* pandas
* numpy
* matplotlib
* stockstats
* OpenAI gym
* stable-baselines
* tensorflow
* pyfolio

<a id='1.3'></a>
## 2.3. Import Packages

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
# matplotlib.use('Agg')
import datetime
from torch import nn
from torch import optim
from torch.nn import functional as F
from torch.utils.data import Dataset, DataLoader

%matplotlib inline
from finrl.config_tickers import DOW_30_TICKER
from finrl.meta.preprocessor.yahoodownloader import YahooDownloader
from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split
from finrl.meta.env_stock_trading.env_stocktrading_initial import StockTradingEnv
from finrl.agents.stablebaselines3.models_initial import DRLAgent,DRLEnsembleAgent
from finrl.plot import backtest_stats, backtest_plot, get_daily_return, get_baseline

from pprint import pprint

import sys
sys.path.append("../FinRL-Library")

import itertools

<a id='1.4'></a>
## 2.4. Create Folders

In [3]:
import os
from finrl.main import check_and_make_directories
from finrl.config import (
    DATA_SAVE_DIR,
    TRAINED_MODEL_DIR,
    TENSORBOARD_LOG_DIR,
    RESULTS_DIR,
    INDICATORS,
    TRAIN_START_DATE,
    TRAIN_END_DATE,
    TEST_START_DATE,
    TEST_END_DATE,
    TRADE_START_DATE,
    TRADE_END_DATE,
)

check_and_make_directories([DATA_SAVE_DIR, TRAINED_MODEL_DIR, TENSORBOARD_LOG_DIR, RESULTS_DIR])

<a id='2'></a>
# Part 3. Download Data
Yahoo Finance is a website that provides stock data, financial news, financial reports, etc. All the data provided by Yahoo Finance is free.
* FinRL uses a class **YahooDownloader** to fetch data from Yahoo Finance API
* Call Limit: Using the Public API (without authentication), you are limited to 2,000 requests per hour per IP (or up to a total of 48,000 requests a day).




-----
class YahooDownloader:
    Provides methods for retrieving daily stock data from
    Yahoo Finance API

    Attributes
    ----------
        start_date : str
            start date of the data (modified from config.py)
        end_date : str
            end date of the data (modified from config.py)
        ticker_list : list
            a list of stock tickers (modified from config.py)

    Methods
    -------
    fetch_data()
        Fetches data from yahoo API


In [ ]:
print(DOW_30_TICKER)

In [ ]:
df = pd.read_csv('merged_df.csv')
df

In [4]:
TRAIN_START_DATE = '2012-10-10'
TRAIN_END_DATE = '2020-02-28'
TRADE_START_DATE = '2020-03-01'
TRADE_END_DATE = '2022-05-30'

In [5]:
import tushare as ts
ts.set_token('6314756019e50a6672690e5a78b2dbf7cfcd27c6f6a6b48a8cf76dae')
pro = ts.pro_api()

In [6]:
#选择上证50指数的成分股
df_index = pro.index_weight(index_code='000016.sh', start_date='20121010', end_date='20220228')
# df_index.to_csv('SSE_50_index_weight.csv',index=0)

In [7]:
#选择某个时间点的上证50指数成分股作为参考跟踪股票池
select_date = '20200228' #自定义的时间点为每个月的月末
df_select = df_index[df_index['trade_date']==select_date]
sort_SSEindex = df_select['con_code'].unique()
print(sort_SSEindex,len(sort_SSEindex))

['603993.SH' '603259.SH' '601989.SH' '601988.SH' '601939.SH' '601888.SH'
 '601857.SH' '601818.SH' '601766.SH' '601688.SH' '601668.SH' '601628.SH'
 '601601.SH' '601398.SH' '601390.SH' '601336.SH' '601328.SH' '601319.SH'
 '601318.SH' '601288.SH' '601236.SH' '601211.SH' '601186.SH' '601166.SH'
 '601138.SH' '601111.SH' '601088.SH' '601066.SH' '601012.SH' '600887.SH'
 '600837.SH' '600703.SH' '600690.SH' '600585.SH' '600547.SH' '600519.SH'
 '600340.SH' '600309.SH' '600276.SH' '600196.SH' '600104.SH' '600050.SH'
 '600048.SH' '600036.SH' '600031.SH' '600030.SH' '600028.SH' '600016.SH'
 '600009.SH' '600000.SH'] 50


In [8]:
#随机选择成分股中的k只股票
import random 
k = 20
selected_tics = random.sample(list(sort_SSEindex),k)
print(selected_tics)

['600837.SH', '600690.SH', '601336.SH', '601211.SH', '600340.SH', '601390.SH', '600030.SH', '601939.SH', '603993.SH', '601166.SH', '601066.SH', '601186.SH', '601328.SH', '600031.SH', '600519.SH', '601236.SH', '601319.SH', '600048.SH', '600276.SH', '601012.SH']


In [9]:
#Download随机选择的k只股票数据
df_ts =pd.DataFrame()
for c in selected_tics:
    temp=pro.daily(ts_code=c,start_date=TRAIN_START_DATE,end_date=TRADE_END_DATE)
    df_ts=pd.concat([df_ts,temp])
print(df_ts)

        ts_code trade_date   open   high    low  close  pre_close  change  \
0     600837.SH   20211231  12.29  12.33  12.24  12.26      12.23    0.03   
1     600837.SH   20211230  12.13  12.30  12.13  12.23      12.16    0.07   
2     600837.SH   20211229  12.17  12.20  12.12  12.16      12.17   -0.01   
3     600837.SH   20211228  12.14  12.19  12.07  12.17      12.11    0.06   
4     600837.SH   20211227  12.05  12.14  12.05  12.11      12.06    0.05   
...         ...        ...    ...    ...    ...    ...        ...     ...   
2323  601012.SH   20120417  19.40  19.54  18.88  18.88      19.45   -0.57   
2324  601012.SH   20120416  19.70  19.85  19.38  19.45      19.74   -0.29   
2325  601012.SH   20120413  19.35  19.85  19.32  19.74      19.47    0.27   
2326  601012.SH   20120412  19.30  19.60  19.15  19.47      19.75   -0.28   
2327  601012.SH   20120411  19.51  20.25  19.35  19.75      21.00   -1.25   

      pct_chg        vol      amount  
0      0.2453  370912.03  455646.954

In [ ]:
# 筛选exchange_calender中每个交易节点缺失情况(全部补充0)
def processed_date(df,selected_tics,k):
    date_unique = list(df['trade_date'].unique())
    date_sum = len(date_unique)
    count = 0
    processe_df =[]
    processed_df = pd.DataFrame()
    for date in date_unique:
        temp_df = df[df['trade_date'] == date]
        if len(temp_df) != k:
            missing_tic = set(selected_tics).difference(set(temp_df['ts_code'].tolist()))
#             print(missing_tic)
            for m_tic in missing_tic:
                temp_dict = {'ts_code':m_tic,'trade_date':date,'open':0, 'high':0,'low':0, 'close':0, 'pre_close':0, 'change':0, 'pct_chg':0, 'volume':0, 'amount':0}
                new_data = pd.DataFrame.from_dict(temp_dict,orient='index').T
                temp_df = temp_df.append(new_data)
            processe_df.append(temp_df)
        else :
            processe_df.append(temp_df)
        processed_df = pd.concat(processe_df,ignore_index = True)       
    processed_df = processed_df.sort_values('trade_date',ascending=True).reset_index()
    processed_df = processed_df.drop('index',axis=1)
    return processed_df,date_unique

In [10]:
# 筛选exchange_calender中每个交易节点缺失(激进)
def processed_date(df,selected_tics,k):
    date_unique = list(df['trade_date'].unique())
    date_sum = len(date_unique)
    count = 0
    processe_df =[]
    processed_df = pd.DataFrame()
    for date in date_unique:
        temp_df = df[df['trade_date'] == date]
        if len(temp_df) == k:
            processe_df.append(temp_df)
        else :
            date_unique.remove(date)
        processed_df = pd.concat(processe_df,ignore_index = True)       
    processed_df = processed_df.sort_values('trade_date',ascending=True).reset_index()
    processed_df = processed_df.drop('index',axis=1)
    return processed_df,date_unique

In [11]:
processed_df,date_unique = processed_date(df_ts,selected_tics,k)
print(processed_df) 

         ts_code trade_date   open   high    low  close  pre_close  change  \
0      601012.SH   20190705  22.40  22.65  22.23  22.41      22.28    0.13   
1      600837.SH   20190705  13.84  14.08  13.74  13.86      13.79    0.07   
2      600690.SH   20190705  17.86  17.95  17.66  17.78      17.78    0.00   
3      601336.SH   20190705  54.50  54.97  54.04  54.73      54.39    0.34   
4      601211.SH   20190705  18.23  18.23  17.97  18.03      18.23   -0.20   
...          ...        ...    ...    ...    ...    ...        ...     ...   
11635  600048.SH   20211231  15.06  15.88  15.05  15.63      15.10    0.53   
11636  600276.SH   20211231  50.20  50.98  49.99  50.71      50.01    0.70   
11637  601012.SH   20211231  84.00  87.33  84.00  86.20      81.23    4.97   
11638  601066.SH   20211231  29.40  29.49  29.20  29.25      29.29   -0.04   
11639  600837.SH   20211231  12.29  12.33  12.24  12.26      12.23    0.03   

       pct_chg         vol        amount  
0       0.5835   234

In [12]:
processed_df1 = processed_df
processed_df1 = processed_df1.sort_values(['ts_code','trade_date'],ascending=True,ignore_index=True)
processed_df1['trade_date'] = pd.to_datetime(processed_df1['trade_date'])
processed_df1

ts_code trade_date   open   high    low  close  pre_close  change  \
0      600030.SH 2019-07-05  23.62  23.75  23.30  23.54      23.60   -0.06   
1      600030.SH 2019-07-08  23.48  23.65  22.90  23.17      23.54   -0.37   
2      600030.SH 2019-07-09  23.35  23.44  22.92  23.23      23.17    0.06   
3      600030.SH 2019-07-10  23.34  23.40  23.04  23.20      23.23   -0.03   
4      600030.SH 2019-07-11  23.40  23.64  22.99  23.18      23.20   -0.02   
...          ...        ...    ...    ...    ...    ...        ...     ...   
11635  603993.SH 2021-12-27   5.54   5.57   5.51   5.52       5.54   -0.02   
11636  603993.SH 2021-12-28   5.55   5.61   5.52   5.57       5.52    0.05   
11637  603993.SH 2021-12-29   5.55   5.59   5.52   5.53       5.57   -0.04   
11638  603993.SH 2021-12-30   5.54   5.56   5.52   5.53       5.53    0.00   
11639  603993.SH 2021-12-31   5.55   5.60   5.53   5.58       5.53    0.05   

       pct_chg         vol       amount  
0      -0.2542   827339.52  1947899.039  
1      -1.5718  1289454.14  3000007.851  
2       0.2590   957241.69  2220341.816  
3      -0.1291   786532.11  1825237.650  
4      -0.0862  1237520.35  2885829.479  
...        ...         ...          ...  
11635  -0.3610   763572.67   422781.670  
11636   0.9058   970692.11   539453.122  
11637  -0.7181   877208.04   486746.356  
11638   0.0000   737165.36   408493.643  
11639   0.9042   862563.77   480126.739  

[11640 rows x 11 columns]

In [ ]:
#出现缺失值的个数、占比
count = len(pro_df[pro_df['open'] == 0])
nan_rate = count/len(pro_df)
print(count,'缺失值百分之:',nan_rate)

In [13]:
fe = FeatureEngineer(
                    use_technical_indicator=True,
                    tech_indicator_list = INDICATORS,
                    use_vix=False,
                    use_turbulence=False,
                    user_defined_feature = False)

In [14]:
processed_df3 = processed_df1.rename(columns={'ts_code':'tic','trade_date':'date','vol':'volume'})
processed_df3 = fe.preprocess_data(processed_df3)
processed_df3 = processed_df3.fillna(method="ffill").fillna(method="bfill")
processed_df3 = processed_df3.sort_values(['tic','date'],ascending=True).reset_index()

Successfully added technical indicators


In [15]:
def delaydate(dela,full_list):
    grouped = processed_df3.groupby('tic')
    filtered_df = pd.DataFrame()
    for name, group in grouped:
        # 按'trade_date'升序排序  True=升序
        group = group.sort_values('date', ascending=True)
        
        # 丢弃前48个日期的数据
        group = group.iloc[dela:]
        filtered_df = filtered_df.append(group)
    
    filtered_df = filtered_df.reset_index(drop=True)
    filtered_df = filtered_df.sort_values(['tic','date'],ascending=True,ignore_index=True)
    return filtered_df

In [16]:
pro_df = processed_df1.loc[:,['open','high','low','close','vol']].reset_index(drop=True)

In [17]:
#计算技术指标到dataset中
#Can be easily expanded
#Currently contains a small set of tech indicators
import talib as ta

def calc_tech_ind(data):
    #overlap 
    data['upbd'], data['midbd'], data['lowbd'] = ta.BBANDS(data["close"])
    data['dema'] = ta.DEMA(data["close"], timeperiod=30)
    data['tema'] = ta.TEMA(data["close"], timeperiod=30)
    data['ema'] = ta.EMA(data["close"], timeperiod=30)
    data['wma'] = ta.WMA(data["close"], timeperiod=30)
    data['sma'] = ta.SMA(data["close"], timeperiod=30)
    data['sarext'] = ta.SAREXT(data["high"], data["low"])
    
    #momentum
    data['adxr'] = ta.ADXR(data["high"], data["low"], data["close"], timeperiod=14)
    data['apo'] = ta.APO(data["close"], fastperiod=12, slowperiod=26, matype=0)
    data['aroondown'], data['aroonup'] = ta.AROON(data["high"], data["low"], timeperiod=14)
    data['cci'] = ta.CCI(data["high"], data["low"], data["close"], timeperiod=14)
    data['cmo'] = ta.CMO(data["close"], timeperiod=14)
    data['macd'], data['macdsignal'], data['macdhist'] = ta.MACD(data["close"], fastperiod=12, slowperiod=26, signalperiod=9)
    data['MFI'] = ta.MFI(data["high"], data["low"], data["close"], data['vol'], timeperiod=14)
    data['mom'] = ta.MOM(data["close"], timeperiod=10)
    data['plus_di'] = ta.PLUS_DI(data["high"], data["low"], data["close"], timeperiod=14)
    data['ppo'] = ta.PPO(data["close"], fastperiod=12, slowperiod=26, matype=0)
    data['roc'] = ta.ROC(data["close"], timeperiod=10)
    data['rocp'] = ta.ROCP(data["close"], timeperiod=10)
    data['rsi'] = ta.RSI(data["close"], timeperiod=14)
    data['slowk'], data['slowd'] = ta.STOCH(data["high"], data["low"], data["close"])
    data['fastk'], data['fastd'] = ta.STOCHF(data["high"], data["low"], data["close"])
    data['trix'] = ta.TRIX(data["close"], timeperiod=30)
    data['ultosc'] = ta.ULTOSC(data["high"], data["low"], data["close"], timeperiod1=7, timeperiod2=14, timeperiod3=28)
    data['willr'] = ta.WILLR(data["high"], data["low"], data["close"], timeperiod=14)
    
    #volume
    data['ad'] = ta.AD(data["high"], data["low"], data["close"], data['vol'])
    data['obv'] = ta.OBV(data["close"], data['vol'])
    
    #volitility
    data['atr'] = ta.ATR(data["high"], data["low"], data["close"], timeperiod=14)
    data['natr'] = ta.NATR(data["high"], data["low"], data["close"], timeperiod=14)
    
    #cycle
    data['HT_DCPERIOD'] = ta.HT_DCPERIOD(data["close"])
#     data['HT_DCPHASE'] = ta.HT_DCPHASE(data["close"])
#     data['inphase'], data['quadrature'] = ta.HT_PHASOR(data["close"])
    
    
    return data

In [18]:
full_list1 = calc_tech_ind(pro_df)
full_list1 = full_list1.fillna(0)

In [19]:
array_full_list = np.array(full_list1)
array_full_list = array_full_list.reshape(k,int(len(full_list1)/k),full_list1.shape[1])
selected_tics = sorted(selected_tics)

In [ ]:
df.tic.value_counts()

# Part 2: DeepLearning representation


In [20]:
#generate x, y, z, zp quadruples
#segment x, y, z trios to sequence according to $timeStep and $gap
#x: historical data w/ technical analysis indicator
#y: closing price of t+1
#z:  difference between t+1 and t step's closing price

def toSequential_train1(idx, full_list, timeStep=48, gap=4):
    #closing: from id=0 to last
    closing=full_list[idx][:, 3]
#     closingNorm = (closing - closing.mean())/closing.std()
    #data from id=0 to second to last
    data=full_list[idx][:-1]
    #calculating number of available sequential samples
    data_length=len(data)
    count=(data_length-timeStep)//gap+1
    stockSeq=[]
    labelSeq=[]
    diffSeq=[]
    realDiffSeq=[]
    for i in range(count):
        #segData dims: [timestep, feature count]       
        segData=data[gap*i:gap*i+timeStep]
        segClosing=closing[gap*i:gap*i+timeStep+1]
        #segDiff=diff[gap*i:gap*i+timeStep]
        #normalization
        
        std_dev = segData.std(axis=0, keepdims=True)
        std_dev_nonzero = np.where(std_dev == 0, 1, std_dev)  # 处理分母为零的情况
#         segDataNorm = np.nan_to_num((segData - segData.mean(axis=0, keepdims=True)) / std_dev_nonzero)
        segDataNorm=np.nan_to_num((segData-segData.mean(axis=0, keepdims=True))/segData.std(axis=0, keepdims=True))
    
        std_close = segClosing.std()
        std_segClosing = np.where(std_close == 0, 1, std_close)
        segClosingNorm=(segClosing-segClosing.mean())/std_segClosing
#         segDiff=(segDiff-segDiff.mean())/segDiff.std()
        
        stockSeq.append(segDataNorm)
        labelSeq.append(segClosingNorm[1:])
        diffSeq.append(segClosingNorm[1:]-segClosingNorm[:-1])
        realDiffSeq.append(segClosing[1:]-segClosing[:-1])
    stockSeq=np.array(stockSeq)
    labelSeq=np.array(labelSeq)
    diffSeq=np.array(diffSeq)
    realDiffSeq=np.array(realDiffSeq)
    return stockSeq.astype('float32') , labelSeq.astype('float32'), diffSeq.astype('float32'), realDiffSeq.astype('float32')

In [21]:
def toSequential_back(idx, full_list, timeStep = 48, gap = 1,batch_size = 64):
    #closing: from id=0 to last
    closing=full_list[idx][:, 3]
    #data from id=0 to second to last
    data=full_list[idx][:-1]
    #calculating number of available sequential samples
    data_length=len(data)
    count=(data_length-timeStep)//gap+1
    stockSeq=[]
    labelSeq=[]
    diffSeq=[]
    realDiffSeq=[]
    
    start = data_length - timeStep
    i=0
    while start >= 0:
        segData = data[start:start + timeStep]
        std_dev = segData.std(axis=0, keepdims=True)
        std_dev_nonzero = np.where(std_dev == 0, 1, std_dev)  # 处理分母为零的情况
        segDataNorm = np.nan_to_num((segData - segData.mean(axis=0, keepdims=True)) / std_dev_nonzero)
        #复制batch_size个
        stockSeq.extend([segDataNorm] * batch_size)
#         stockSeq.append(segDataNorm)   
        start = start - gap
        i +=1
    stockSeq=np.array(stockSeq)[::-1]
#     print(i)
    return stockSeq.astype('float32')

In [22]:
#input each step:  vector including [stock info, tech indicators]
#output each step: closing price t+1, price diff between t+1 and t
#full_list: output from get_data_set

class StockDataset(Dataset):
    def __init__(self, id_list, full_list, transform=None, timestep=48, gap=3):
        self.transform=transform
        self.id_list=id_list
        
        stock_cohort=[]
        closing_cohort=[]
        diff_cohort=[]
        real_diff_cohort=[]
        
        #load data into cohort
        for i in self.id_list:
            X, y, z, zp=toSequential_train1(i, full_list, timeStep=timestep, gap=gap)
            stock_cohort.append(X)
            closing_cohort.append(y)
            diff_cohort.append(z)
            real_diff_cohort.append(zp)
        self.X=np.concatenate(stock_cohort, axis=0)
        self.y=np.concatenate(closing_cohort, axis=0)
        self.z=np.concatenate(diff_cohort, axis=0)  
        self.zp=np.concatenate(real_diff_cohort, axis=0)
        
    def __len__(self):
        return len(self.y)
    
    def __getitem__(self, idx):
        """
        data returned in the format of 
        """
        if torch.is_tensor(idx):
            idx=idx.tolist()
        
        data=self.X[idx]
        label1=self.y[idx]
        label2=self.z[idx]
        label3=self.zp[idx]
        if self.transform:
            data=self.transform(data)
        return (data, label1, label2, label3)
    
    
    def getDS(self):
        return self.X, self.y, self.z, self.zp

In [23]:
#input each step:  vector including [stock info, tech indicators]
#output each step: closing price t+1, price diff between t+1 and t
#full_list: output from get_data_set

class StockDataset_back(Dataset):
    def __init__(self, id_list, full_list, transform=None, timestep=48, gap=1):
        self.transform=transform
        self.id_list=id_list
        
        stock_cohort=[]
        
        #load data into cohort
        for i in self.id_list:
            X=toSequential_back(i, full_list, timeStep=timestep, gap=gap)
            stock_cohort.append(X)
        self.X=np.concatenate(stock_cohort, axis=0)
        
    def __len__(self):
        return len(self.X)
    
    def __getitem__(self, idx):
        """
        data returned in the format of 
        """
        if torch.is_tensor(idx):
            idx=idx.tolist()
        
        data=self.X[idx]
        if self.transform:
            data=self.transform(data)
        return data
        
    def getDS(self):
        return self.X

In [24]:
#Generation of training, validation, and testing dataset
def DataIterGen(test_id_list, val_id_list, name_list, full_list, demo=False):
    """
    test_id_list: id of subjects for testing
    val_id_list: id of subjects for validation
    other subjects for training
    full_list=get_data_set(name_list), preprocessed
    demo: when demo mode is True, only test_iter is returned, with data from
    first entry of test_id_list (single stock)
    """
    name_count=len(name_list)

    if demo:
        test_iter=DataLoader(StockDataset(test_id_list[0:1], full_list, timestep=24, gap=1), shuffle=False, batch_size=64, num_workers=0)
        print(f'Demo with stock: {name_list[test_id_list[0]]} ')
        return test_iter
    else:
        all_ids = list(range(name_count))
        train_id_list = list(set(all_ids) - set(test_id_list) - set(val_id_list))
#         partial_list=full_list[train_list,:,:]
        test_iter=DataLoader(StockDataset(test_id_list, full_list), batch_size=64, num_workers=0,drop_last=True)
        val_iter=DataLoader(StockDataset(val_id_list, full_list), batch_size=64, num_workers=0,drop_last=True)
        train_iter=DataLoader(StockDataset(train_id_list, full_list), shuffle=True, batch_size=64, num_workers=0,drop_last=True)
        print(f'Val: {[name_list[val_id] for val_id in val_id_list]}, Test: {[name_list[test_id] for test_id in test_id_list]}, Train: {[name_list[train_id] for train_id in train_id_list]} ')
        return train_iter, val_iter, test_iter

In [25]:
train_iter, val_iter, test_iter = DataIterGen([3],[4],selected_tics,array_full_list)

Val: ['600340.SH'], Test: ['600276.SH'], Train: ['600030.SH', '600031.SH', '600048.SH', '600519.SH', '600690.SH', '600837.SH', '601012.SH', '601066.SH', '601166.SH', '601186.SH', '601211.SH', '601236.SH', '601319.SH', '601328.SH', '601336.SH', '601390.SH', '601939.SH', '603993.SH'] 


# Part3: Transformer

In [45]:
# import torch
# import torch.nn as nn
# import torch.nn.functional as F

# class TransformerEncoder(nn.Module):
#     def __init__(self, input_size, d_model, num_heads, num_layers,dropout_rate):
#         super(TransformerEncoder, self).__init__()
#         self.embedding = nn.Linear(input_size, d_model)
#         self.attention = nn.MultiheadAttention(d_model, num_heads)
#         self.dropout1 = nn.Dropout(dropout_rate)
#         self.layer_norm1 = nn.LayerNorm(d_model)
#         self.feed_forward = nn.Sequential(
#             nn.Linear(d_model, d_moedl * 4),
#             nn.ReLU(),
#             nn.Linear(d_model * 4, d_model)
#         )
#         self.dropout2 = nn.Dropout(dropout_rate)
#         self.layer_norm2 = nn.LayerNorm(d_moedl)
#         self.num_layers = num_layers

#     def forward(self, x):
#         x = self.embedding(x)
#         for _ in range(self.num_layers):
#             residual = x
#             x, _ = self.attention(x, x, x)
#             x = self.dropout1(x)
#             x = self.layer_norm1(x + residual)
#             residual = x
#             x = self.feed_forward(x)
#             x = self.dropout2(x)
#             x = self.layer_norm2(x + residual)
#         return x


In [46]:
# class TransformerDecoder(nn.Module):
#     def __init__(self, input_size, d_model, num_heads, env_size, num_layers, dropout_rate):
#         super(TransformerDecoder, self).__init__()
#         self.embedding = nn.Linear(input_size, d_model)
#         self.attention = nn.MultiheadAttention(d_model, num_heads)
#         self.dropout1 = nn.Dropout(dropout_rate)
#         self.layer_norm1 = nn.LayerNorm(d_model)
#         self.encoder_attention = nn.MultiheadAttention(d_model, num_heads)
#         self.dropout2 = nn.Dropout(dropout_rate)
#         self.layer_norm2 = nn.LayerNorm(d_model)
#         self.feed_forward = nn.Sequential(
#             nn.Linear(d_model, d_model * 4),
#             nn.ReLU(),
#             nn.Linear(d_model * 4, d_model)
#         )
#         self.dropout3 = nn.Dropout(dropout_rate)
#         self.layer_norm3 = nn.LayerNorm(d_model)
#         self.linear1 = nn.Linear(d_model, env_size)
#         self.linear2 = nn.Linear(env_size,1)
#         self.num_layers = num_layers

#     def forward(self, x, encoder_output, target_mask, target_padding_mask):
#         x = self.embedding(x)
#         for _ in range(self.num_layers):
#             residual = x
#             x, _ = self.attention(x, x, x, attn_mask=target_mask)
#             x = self.dropout1(x)
#             x = self.layer_norm1(x + residual)
#             residual = x
#             x, _ = self.encoder_attention(x, encoder_output, encoder_output,key_padding_mask =target_padding_mask)
#             x = self.dropout2(x)
#             x = self.layer_norm2(x + residual)
#             residual = x
#             x = self.feed_forward(x)
#             x = self.dropout3(x)
#             x = self.layer_norm3(x + residual)
#         env_size = self.linear1(x)
#         x = self.linear2(env_size).permute(1,0,2)
#         return x, env_size.permute(1,0,2)[0,-1,:]  


In [47]:
# class Transformer(nn.Module):
#     def __init__(self, input_size, d_model, num_heads, num_layers, env_size, dropout_rate):
#         super(Transformer, self).__init__()
#         self.encoder = TransformerEncoder(input_size, d_model, num_heads, num_layers,dropout_rate)
#         self.decoder = TransformerDecoder(input_size, d_model, num_heads, env_size, num_layers,dropout_rate)

#     def forward(self, input_seq, target_seq):
#         encoder_output = self.encoder(input_seq)
#         target_mask = self.generate_attention_mask(target_seq)
#         target_padding_mask = self.generate_padding_mask(target_seq)
#         decoder_output = self.decoder(target_seq, encoder_output)
#         return decoder_output
    
#     def generate_attention_mask(self, sequence):
#         attn_mask = torch.triu(torch.ones(sequence.size(1), sequence.size(1)), diagonal=1).bool().to(sequence.device)
#         return attn_mask

#     def generate_padding_mask(self, sequence):
#         padding_mask = (sequence == 0).to(sequence.device)
#         return padding_mask

In [38]:
# #模型训练
# def train(model, train_iter, optimizer, num_epochs): 
#     # 训练循环
#     for epoch in range(num_epochs):
#         model.train()
#         total_loss = 0.0
#         enVec_list = []
#         for X, y, z, zp in train_iter:  
#             optimizer.zero_grad()

#             inputs = X.to(device)
#             targets = y.unsqueeze(2).to(device)
#             pred,enVec = model(inputs,targets)
#             enVec_list.append(enVec)
#             print(pred,targets)
#             loss = nn.MSELoss()(pred, targets)  
#             loss.backward()
#             optimizer.step()
#             total_loss += loss.item()

#         # 打印每个 epoch 的损失
#         print(f"Epoch {epoch+1}: Loss: {total_loss/len(train_iter):.4f}")
#     return enVec_list
# # 模型评估
# def val(model, val_iter):
#     model.eval()
#     total_loss = 0.0
#     enVec_list = []
#     with torch.no_grad():
#         for X, y, z, zp in val_iter: 
#             inputs = X.to(device)
#             targets = y.unsqueeze(2).to(device)
#             pred, enVec = model(inputs)
#             enVec_list.append(enVec)
#             loss = nn.MSELoss()(pred, targets)  
#             total_loss += loss.item()
#     print(f"val Loss: {total_loss/len(val_iter):.4f}")
#     return enVec_list

In [39]:
# # 定义模型
# model = Transformer(input_size = 42, d_model = 128 , num_layers = 2, num_heads = 8,env_size =40,dropout_rate=0.2)
# optimizer = optim.Adam(model.parameters(), lr=0.001)
# outcoming =train(model,train_iter,optimizer,5)
# valtest =val(model,val_iter)

tensor([[[-0.0846],
         [-0.1001],
         [-0.2599],
         ...,
         [-0.0039],
         [ 0.0340],
         [ 0.1109]],

        [[ 0.0624],
         [-0.0389],
         [-0.0283],
         ...,
         [-0.1571],
         [-0.1198],
         [-0.1610]],

        [[ 0.0123],
         [-0.2264],
         [-0.1915],
         ...,
         [-0.1144],
         [-0.1178],
         [-0.0976]],

        ...,

        [[-0.0366],
         [ 0.0441],
         [ 0.1223],
         ...,
         [ 0.1144],
         [-0.0274],
         [-0.0300]],

        [[-0.0626],
         [-0.0996],
         [-0.0754],
         ...,
         [-0.1084],
         [-0.0288],
         [ 0.0161]],

        [[ 0.2461],
         [ 0.1232],
         [ 0.0470],
         ...,
         [ 0.0235],
         [ 0.0386],
         [ 0.0011]]], grad_fn=<PermuteBackward0>) tensor([[[-0.5165],
         [-0.3840],
         [-0.4944],
         ...,
         [ 1.1398],
         [ 1.5594],
         [ 2.4206]],

      

tensor([[[ 0.4296],
         [ 0.0981],
         [ 0.0752],
         ...,
         [-0.1770],
         [-0.0858],
         [-0.1805]],

        [[-1.0848],
         [-1.1203],
         [-0.7930],
         ...,
         [-1.0225],
         [-1.1106],
         [-0.5233]],

        [[ 1.3774],
         [ 1.4190],
         [ 1.2999],
         ...,
         [-0.5515],
         [-0.2509],
         [-0.1949]],

        ...,

        [[-1.2182],
         [-1.2097],
         [-1.2279],
         ...,
         [-1.0025],
         [-0.9801],
         [-0.9199]],

        [[-1.0775],
         [-0.9518],
         [-0.4702],
         ...,
         [-0.4013],
         [-0.6632],
         [-0.6271]],

        [[-0.6705],
         [-0.5228],
         [-0.5712],
         ...,
         [ 1.5484],
         [ 1.5140],
         [ 1.4902]]], grad_fn=<PermuteBackward0>) tensor([[[-0.2978],
         [-0.0272],
         [-0.0306],
         ...,
         [ 0.0168],
         [-0.0475],
         [-0.4838]],

      

tensor([[[-0.8782],
         [-0.7640],
         [-0.7511],
         ...,
         [-0.0329],
         [-0.3541],
         [ 0.4400]],

        [[ 0.4924],
         [ 0.3773],
         [-0.1836],
         ...,
         [ 0.7657],
         [ 0.2568],
         [-0.1693]],

        [[ 1.1770],
         [ 1.4574],
         [ 1.4603],
         ...,
         [-0.7345],
         [-0.8181],
         [-0.8234]],

        ...,

        [[ 1.1166],
         [ 0.9557],
         [ 0.7321],
         ...,
         [-0.4509],
         [-0.5768],
         [-0.6881]],

        [[-0.8783],
         [-0.7105],
         [-0.7517],
         ...,
         [ 1.3007],
         [ 1.2070],
         [ 1.0921]],

        [[-0.6715],
         [-0.6118],
         [ 0.3136],
         ...,
         [-0.7216],
         [-0.8854],
         [-0.7725]]], grad_fn=<PermuteBackward0>) tensor([[[-0.6918],
         [-0.7782],
         [-0.0875],
         ...,
         [-0.2170],
         [ 0.4449],
         [ 0.5312]],

      

tensor([[[-0.8651],
         [-0.4618],
         [-0.9120],
         ...,
         [ 0.3640],
         [ 0.6237],
         [ 0.6067]],

        [[-0.3111],
         [-0.1005],
         [-0.1417],
         ...,
         [ 0.6957],
         [ 1.0747],
         [ 1.3439]],

        [[ 0.7071],
         [ 0.6067],
         [ 0.3986],
         ...,
         [ 0.8126],
         [ 1.1224],
         [ 1.2175]],

        ...,

        [[ 0.6220],
         [ 0.1013],
         [-0.3312],
         ...,
         [-0.2812],
         [-0.8759],
         [-1.1439]],

        [[ 1.2766],
         [ 1.1272],
         [ 1.4515],
         ...,
         [-1.1545],
         [-1.2286],
         [-1.1698]],

        [[-0.3874],
         [-0.5325],
         [-0.7319],
         ...,
         [ 1.4247],
         [ 1.6337],
         [ 1.6958]]], grad_fn=<PermuteBackward0>) tensor([[[-0.5318],
         [-0.9442],
         [-1.0768],
         ...,
         [ 1.2505],
         [ 1.0885],
         [ 0.4699]],

      

tensor([[[ 0.0506],
         [ 0.3350],
         [ 0.9116],
         ...,
         [-0.6998],
         [-0.6828],
         [-0.6790]],

        [[ 1.1230],
         [ 1.2485],
         [ 1.2563],
         ...,
         [-0.2248],
         [ 0.3721],
         [ 0.4567]],

        [[-0.0102],
         [-0.4879],
         [ 0.6411],
         ...,
         [ 0.1731],
         [ 0.0478],
         [-0.0146]],

        ...,

        [[-0.6464],
         [-0.5395],
         [-0.5971],
         ...,
         [ 0.8244],
         [ 0.7431],
         [ 0.5215]],

        [[ 0.3356],
         [ 0.1216],
         [-0.0333],
         ...,
         [ 0.2644],
         [ 0.0498],
         [-0.2611]],

        [[-0.5533],
         [-0.2612],
         [-0.5973],
         ...,
         [-0.3903],
         [-1.0371],
         [-0.4041]]], grad_fn=<PermuteBackward0>) tensor([[[ 0.0199],
         [ 1.8989],
         [ 1.5659],
         ...,
         [-0.8760],
         [-0.8046],
         [-0.8363]],

      

tensor([[[ 0.0828],
         [ 0.2173],
         [-0.0650],
         ...,
         [ 1.8771],
         [ 1.9459],
         [ 1.8874]],

        [[ 0.1494],
         [-0.5241],
         [-0.3084],
         ...,
         [ 1.6774],
         [ 1.6059],
         [ 1.5056]],

        [[ 0.4049],
         [ 0.7043],
         [ 0.7388],
         ...,
         [-0.6806],
         [-0.7565],
         [-0.7883]],

        ...,

        [[-1.0604],
         [-0.8503],
         [-1.0824],
         ...,
         [-0.0891],
         [-0.6400],
         [-1.1631]],

        [[ 1.1538],
         [ 1.0260],
         [ 1.2220],
         ...,
         [-1.0119],
         [-0.9509],
         [-0.6353]],

        [[ 0.6671],
         [ 0.1104],
         [ 0.2321],
         ...,
         [-1.5579],
         [-1.5926],
         [-1.5806]]], grad_fn=<PermuteBackward0>) tensor([[[ 0.1416],
         [-0.2064],
         [-0.2227],
         ...,
         [ 2.8281],
         [ 2.8661],
         [ 3.2196]],

      

tensor([[[-1.1438],
         [-0.5035],
         [-0.4198],
         ...,
         [-0.3701],
         [ 0.1873],
         [ 0.8802]],

        [[-0.1876],
         [-0.6504],
         [-1.1063],
         ...,
         [-0.3429],
         [-0.8474],
         [-0.5324]],

        [[ 0.8566],
         [-0.7945],
         [-0.5566],
         ...,
         [-1.1786],
         [-0.8739],
         [-0.9827]],

        ...,

        [[ 1.0451],
         [ 0.6315],
         [ 0.4494],
         ...,
         [-0.3547],
         [-1.5097],
         [-1.2875]],

        [[ 1.4758],
         [ 1.6893],
         [ 1.5665],
         ...,
         [-0.2086],
         [-0.3376],
         [-0.3323]],

        [[ 1.1696],
         [ 1.4725],
         [ 1.2369],
         ...,
         [-1.2159],
         [-1.1101],
         [-1.0684]]], grad_fn=<PermuteBackward0>) tensor([[[-0.5000],
         [-0.4595],
         [-0.5406],
         ...,
         [ 0.0271],
         [ 1.1344],
         [ 0.8990]],

      

tensor([[[-0.5615],
         [-0.6580],
         [-0.8700],
         ...,
         [ 0.8053],
         [ 1.6785],
         [ 1.4886]],

        [[ 1.2445],
         [ 1.0830],
         [ 1.2798],
         ...,
         [-1.6949],
         [-1.7718],
         [-1.8297]],

        [[-0.5346],
         [ 0.0572],
         [ 1.2938],
         ...,
         [-0.3572],
         [ 0.2570],
         [ 0.5046]],

        ...,

        [[-0.6704],
         [-1.1384],
         [-1.0752],
         ...,
         [ 1.4621],
         [ 1.6488],
         [ 1.7623]],

        [[-1.0605],
         [-0.8397],
         [-1.0490],
         ...,
         [ 1.0915],
         [ 0.5893],
         [ 0.1115]],

        [[-0.6386],
         [-0.2320],
         [-0.1757],
         ...,
         [-0.7257],
         [-0.6024],
         [-0.6428]]], grad_fn=<PermuteBackward0>) tensor([[[-0.8098],
         [-1.1677],
         [-1.6993],
         ...,
         [ 2.1535],
         [ 1.5298],
         [ 1.0850]],

      

tensor([[[ 1.0605],
         [ 0.0547],
         [ 0.5179],
         ...,
         [-1.1805],
         [-1.0317],
         [-1.1182]],

        [[-1.0907],
         [-1.1768],
         [-0.9918],
         ...,
         [ 2.2855],
         [ 2.2861],
         [ 2.1802]],

        [[ 0.6871],
         [ 0.6125],
         [ 0.3621],
         ...,
         [ 1.8594],
         [ 2.2888],
         [ 2.3798]],

        ...,

        [[-1.7192],
         [-1.7363],
         [-1.7993],
         ...,
         [ 1.2062],
         [ 1.1967],
         [ 1.1489]],

        [[ 1.1232],
         [ 0.2032],
         [ 0.0107],
         ...,
         [ 0.2192],
         [-0.0773],
         [-0.0197]],

        [[ 1.3142],
         [ 1.2646],
         [ 1.2338],
         ...,
         [-1.3360],
         [-1.2935],
         [-1.5130]]], grad_fn=<PermuteBackward0>) tensor([[[ 0.1672],
         [ 0.3852],
         [ 0.4786],
         ...,
         [-1.0974],
         [-1.1846],
         [-1.1597]],

      

tensor([[[-0.9521],
         [-1.0073],
         [-0.6006],
         ...,
         [-1.2709],
         [-1.1445],
         [-0.8905]],

        [[ 1.4356],
         [ 1.4474],
         [ 1.5591],
         ...,
         [-1.1428],
         [-1.2119],
         [-1.2761]],

        [[ 1.2585],
         [ 1.3082],
         [ 1.3429],
         ...,
         [-1.0571],
         [-1.6298],
         [-1.7370]],

        ...,

        [[-0.1289],
         [-0.0685],
         [-0.2558],
         ...,
         [-1.3687],
         [-1.6836],
         [-1.8793]],

        [[ 0.2634],
         [-0.6090],
         [-0.6873],
         ...,
         [ 0.0341],
         [-1.1820],
         [-1.3920]],

        [[-1.2093],
         [-1.1953],
         [-1.3850],
         ...,
         [ 0.5157],
         [ 0.6437],
         [ 0.6174]]], grad_fn=<PermuteBackward0>) tensor([[[-1.4181],
         [-0.8939],
         [-0.7711],
         ...,
         [-1.1006],
         [-0.7501],
         [-1.6128]],

      

tensor([[[ 1.3464],
         [ 1.3855],
         [ 1.2305],
         ...,
         [-1.4109],
         [-1.7215],
         [-1.3847]],

        [[ 1.5929],
         [ 0.8824],
         [ 1.0443],
         ...,
         [-1.7055],
         [-1.5055],
         [-1.5216]],

        [[ 1.1055],
         [ 0.9024],
         [ 0.7407],
         ...,
         [-0.7452],
         [-1.0894],
         [-1.4474]],

        ...,

        [[ 1.8285],
         [ 1.2854],
         [ 1.1347],
         ...,
         [-0.4201],
         [-0.5439],
         [-0.6673]],

        [[-1.1498],
         [-0.9570],
         [-0.9522],
         ...,
         [ 0.9612],
         [ 0.2782],
         [ 0.5757]],

        [[ 2.0973],
         [ 1.9176],
         [ 1.5723],
         ...,
         [-0.9681],
         [-0.9025],
         [-0.7126]]], grad_fn=<PermuteBackward0>) tensor([[[ 1.1652],
         [ 0.9110],
         [ 0.5720],
         ...,
         [-2.2033],
         [-1.7584],
         [-1.7584]],

      

tensor([[[-0.7840],
         [-0.7458],
         [-0.6657],
         ...,
         [-0.9551],
         [-0.9123],
         [-1.2238]],

        [[-0.3130],
         [-0.3305],
         [-0.2377],
         ...,
         [-1.1791],
         [-0.8308],
         [-0.7848]],

        [[-0.3115],
         [-0.3935],
         [-0.3337],
         ...,
         [-1.3267],
         [-1.3601],
         [-1.0452]],

        ...,

        [[ 0.9970],
         [ 1.0853],
         [ 1.3101],
         ...,
         [-0.6901],
         [-0.3403],
         [-0.3099]],

        [[ 1.0067],
         [ 0.7005],
         [ 0.6695],
         ...,
         [ 1.2819],
         [ 1.1227],
         [ 0.4560]],

        [[-0.8489],
         [-1.1263],
         [-1.0239],
         ...,
         [ 1.0338],
         [ 1.0965],
         [ 0.9467]]], grad_fn=<PermuteBackward0>) tensor([[[-0.8113],
         [-0.5632],
         [-0.6873],
         ...,
         [-0.8527],
         [-1.5142],
         [-2.0931]],

      

tensor([[[ 1.0429],
         [ 1.1737],
         [ 1.3982],
         ...,
         [-1.0839],
         [-1.2944],
         [-1.4664]],

        [[-1.6978],
         [-1.6806],
         [-1.4669],
         ...,
         [ 1.0145],
         [ 1.2779],
         [ 1.0748]],

        [[ 1.0176],
         [ 1.2980],
         [ 1.7009],
         ...,
         [-1.4230],
         [-1.4253],
         [-1.1939]],

        ...,

        [[-1.4291],
         [-1.3819],
         [-1.3099],
         ...,
         [ 1.2868],
         [ 1.1594],
         [ 1.0189]],

        [[ 1.6772],
         [ 0.8896],
         [ 0.7688],
         ...,
         [ 1.3378],
         [ 1.2325],
         [ 1.1978]],

        [[ 1.5791],
         [ 1.4055],
         [ 1.0056],
         ...,
         [ 1.6493],
         [ 1.5088],
         [ 1.2566]]], grad_fn=<PermuteBackward0>) tensor([[[ 1.0968],
         [ 1.6761],
         [ 1.4186],
         ...,
         [-1.0916],
         [-1.4777],
         [-1.4134]],

      

tensor([[[ 1.0037],
         [ 0.9481],
         [ 0.8957],
         ...,
         [ 0.1678],
         [ 0.2122],
         [ 0.1164]],

        [[ 1.6709],
         [ 1.3939],
         [ 1.3183],
         ...,
         [-0.7614],
         [-0.5270],
         [-0.6529]],

        [[-0.7303],
         [-0.7293],
         [-0.7722],
         ...,
         [ 1.1784],
         [ 1.1323],
         [ 1.0072]],

        ...,

        [[-0.9850],
         [-0.9777],
         [-0.9208],
         ...,
         [ 2.1957],
         [ 2.1696],
         [ 2.2254]],

        [[ 0.7360],
         [ 0.5826],
         [ 0.7922],
         ...,
         [-1.4982],
         [-1.4575],
         [-1.2525]],

        [[-0.4066],
         [-0.0102],
         [-0.1641],
         ...,
         [-0.2806],
         [-0.4152],
         [-0.3376]]], grad_fn=<PermuteBackward0>) tensor([[[ 1.1114],
         [ 1.1114],
         [ 0.9274],
         ...,
         [ 0.4215],
         [ 0.2835],
         [ 0.4215]],

      

tensor([[[ 1.1692e+00],
         [ 1.1621e+00],
         [ 1.4239e+00],
         ...,
         [ 1.6631e-03],
         [-1.3459e-04],
         [ 2.5287e-02]],

        [[ 1.3549e+00],
         [ 1.7958e+00],
         [ 1.4678e+00],
         ...,
         [-2.0420e-01],
         [-4.0068e-01],
         [-1.2748e+00]],

        [[ 1.2246e+00],
         [ 1.3791e+00],
         [ 1.2801e+00],
         ...,
         [-5.6166e-01],
         [-5.7736e-01],
         [-7.0560e-01]],

        ...,

        [[ 1.4477e+00],
         [ 1.4368e+00],
         [ 1.3886e+00],
         ...,
         [-6.3320e-01],
         [-7.7450e-01],
         [-8.4076e-01]],

        [[ 1.2049e+00],
         [ 1.2336e+00],
         [ 1.7231e+00],
         ...,
         [-6.5318e-01],
         [-8.5539e-01],
         [-8.3492e-01]],

        [[ 1.8723e+00],
         [ 2.2874e+00],
         [ 1.8744e+00],
         ...,
         [-1.0885e+00],
         [-1.2167e+00],
         [-9.4020e-01]]], grad_fn=<PermuteBackward0>

tensor([[[-0.5726],
         [-0.5490],
         [-0.3684],
         ...,
         [ 1.2859],
         [ 1.3072],
         [ 1.6903]],

        [[ 0.9209],
         [ 1.6469],
         [ 1.4441],
         ...,
         [-1.1661],
         [-1.4202],
         [-1.6865]],

        [[-1.1996],
         [-1.3477],
         [-0.0802],
         ...,
         [-1.4810],
         [-1.2221],
         [-1.2493]],

        ...,

        [[ 0.3759],
         [ 0.5120],
         [ 0.2692],
         ...,
         [ 1.1012],
         [ 1.3336],
         [ 1.9534]],

        [[ 0.9279],
         [ 1.2655],
         [ 1.1807],
         ...,
         [ 0.3033],
         [-0.0870],
         [-0.1281]],

        [[-0.0573],
         [-0.1006],
         [-0.0613],
         ...,
         [ 0.9565],
         [ 0.8310],
         [ 0.7623]]], grad_fn=<PermuteBackward0>) tensor([[[-0.6551],
         [-0.2930],
         [-0.7420],
         ...,
         [ 1.1990],
         [ 2.0971],
         [ 1.4887]],

      

tensor([[[ 0.2667],
         [-0.0479],
         [-1.3400],
         ...,
         [ 0.0738],
         [ 0.3244],
         [ 0.5461]],

        [[-0.2392],
         [-0.3828],
         [-0.2526],
         ...,
         [ 1.5507],
         [ 1.7737],
         [ 1.4969]],

        [[ 1.5402],
         [ 1.3960],
         [ 1.4281],
         ...,
         [-1.0812],
         [-1.1113],
         [-1.6517]],

        ...,

        [[ 1.5289],
         [ 0.9883],
         [ 0.7682],
         ...,
         [ 1.2263],
         [ 1.3605],
         [ 1.7109]],

        [[-1.7588],
         [-1.6901],
         [-1.6757],
         ...,
         [ 0.7477],
         [ 0.6101],
         [ 0.9424]],

        [[ 1.3694],
         [ 1.4571],
         [ 1.2876],
         ...,
         [-1.4623],
         [-1.5648],
         [-1.3938]]], grad_fn=<PermuteBackward0>) tensor([[[ 0.2727],
         [-0.8939],
         [-1.6363],
         ...,
         [ 0.2920],
         [ 0.4366],
         [ 0.0510]],

      

tensor([[[ 1.1268],
         [ 1.1709],
         [ 1.1583],
         ...,
         [-1.0928],
         [-1.1941],
         [-1.2363]],

        [[-0.5663],
         [-0.6804],
         [-0.9737],
         ...,
         [-1.2416],
         [-1.3080],
         [-1.0760]],

        [[-0.2252],
         [-0.3849],
         [-0.5855],
         ...,
         [ 0.0703],
         [-0.2799],
         [-0.2706]],

        ...,

        [[-0.5848],
         [-0.5979],
         [-0.4885],
         ...,
         [-0.5275],
         [-0.8231],
         [-0.7836]],

        [[-0.0338],
         [ 0.1135],
         [ 0.1161],
         ...,
         [-0.9111],
         [-0.8433],
         [-0.6858]],

        [[ 0.0367],
         [ 0.0182],
         [ 0.0902],
         ...,
         [-1.5066],
         [-1.4665],
         [-1.3368]]], grad_fn=<PermuteBackward0>) tensor([[[ 1.4213],
         [ 1.5344],
         [ 1.2894],
         ...,
         [-1.2740],
         [-1.4625],
         [-1.5567]],

      

tensor([[[ 2.5985e+00],
         [ 2.6253e+00],
         [ 2.5018e+00],
         ...,
         [-8.5947e-01],
         [-8.5012e-01],
         [-8.6184e-01]],

        [[-1.3027e+00],
         [-1.2597e+00],
         [-1.2757e+00],
         ...,
         [ 1.6470e+00],
         [ 1.5989e+00],
         [ 1.5583e+00]],

        [[ 1.2678e+00],
         [ 1.2739e+00],
         [ 1.3546e+00],
         ...,
         [-1.7944e-01],
         [-2.8313e-01],
         [-4.2333e-01]],

        ...,

        [[ 1.3249e+00],
         [ 1.4559e+00],
         [ 1.1100e+00],
         ...,
         [-1.6500e-03],
         [-1.9551e-02],
         [-1.1000e-02]],

        [[-2.8556e-02],
         [-7.7850e-02],
         [ 7.4680e-03],
         ...,
         [ 2.1776e+00],
         [ 2.0827e+00],
         [ 1.9725e+00]],

        [[ 1.1952e+00],
         [ 9.2554e-01],
         [ 4.7620e-01],
         ...,
         [ 1.4030e+00],
         [ 1.4531e+00],
         [ 1.2494e+00]]], grad_fn=<PermuteBackward0>

tensor([[[ 0.5068],
         [ 0.0779],
         [-0.0717],
         ...,
         [ 1.0146],
         [ 0.6481],
         [ 0.4470]],

        [[-1.5896],
         [-1.1387],
         [-0.9238],
         ...,
         [-0.5134],
         [-0.6797],
         [-0.2351]],

        [[ 1.3717],
         [ 1.2194],
         [ 1.2449],
         ...,
         [ 0.7721],
         [ 0.9386],
         [ 0.8509]],

        ...,

        [[-0.9068],
         [-0.7954],
         [-0.9921],
         ...,
         [ 0.8118],
         [ 1.1388],
         [ 1.2128]],

        [[ 1.9516],
         [ 1.7930],
         [ 2.2372],
         ...,
         [-0.1441],
         [-0.1595],
         [-0.1283]],

        [[ 1.6391],
         [ 1.6969],
         [ 1.7146],
         ...,
         [-1.0903],
         [-1.0066],
         [-0.9182]]], grad_fn=<PermuteBackward0>) tensor([[[ 0.9047],
         [ 0.5058],
         [-0.9403],
         ...,
         [ 0.7551],
         [ 0.5556],
         [ 0.2565]],

      

tensor([[[ 0.3478],
         [ 0.3096],
         [ 0.4067],
         ...,
         [-1.3129],
         [-1.1776],
         [-1.2534]],

        [[-0.3230],
         [-0.3638],
         [-0.2031],
         ...,
         [-1.3745],
         [-1.1966],
         [-0.9126]],

        [[ 0.3557],
         [ 0.1988],
         [ 1.4062],
         ...,
         [-0.4000],
         [-0.3159],
         [-0.4265]],

        ...,

        [[-1.1525],
         [-1.2151],
         [-1.0563],
         ...,
         [-0.8464],
         [-0.6952],
         [-0.1602]],

        [[ 1.3035],
         [ 1.2524],
         [ 1.1966],
         ...,
         [-1.1046],
         [-1.7929],
         [-1.5388]],

        [[-1.0003],
         [-1.1450],
         [-1.1401],
         ...,
         [ 1.5854],
         [ 1.2501],
         [ 1.1479]]], grad_fn=<PermuteBackward0>) tensor([[[ 0.1389],
         [ 0.1389],
         [-0.1813],
         ...,
         [-1.4621],
         [-1.6221],
         [-1.5421]],

      

tensor([[[ 1.3533],
         [ 2.0047],
         [ 1.8149],
         ...,
         [-0.3490],
         [ 0.0711],
         [-0.0621]],

        [[-1.3654],
         [-0.5217],
         [ 1.4568],
         ...,
         [-1.2804],
         [-1.2119],
         [-1.6381]],

        [[-1.1877],
         [-1.2886],
         [-1.2771],
         ...,
         [-0.7561],
         [-0.5906],
         [-0.5373]],

        ...,

        [[ 0.9846],
         [ 1.1084],
         [ 1.2512],
         ...,
         [-0.8529],
         [-0.9056],
         [-0.8846]],

        [[ 2.0569],
         [ 2.2239],
         [ 2.2534],
         ...,
         [-0.7040],
         [ 0.0309],
         [-0.2827]],

        [[ 1.8378],
         [ 1.9148],
         [ 2.1173],
         ...,
         [-0.9573],
         [-0.8895],
         [-0.8119]]], grad_fn=<PermuteBackward0>) tensor([[[ 2.3593],
         [ 2.3269],
         [ 1.9870],
         ...,
         [ 0.2715],
         [-0.3435],
         [-0.6348]],

      

tensor([[[ 1.9310],
         [ 1.7536],
         [ 1.3759],
         ...,
         [ 0.2038],
         [ 1.2832],
         [ 1.3172]],

        [[ 1.6369],
         [ 1.7661],
         [ 1.8343],
         ...,
         [-0.4125],
         [-0.4670],
         [-0.5532]],

        [[ 0.1344],
         [-0.0220],
         [ 0.0152],
         ...,
         [ 1.2620],
         [ 1.5067],
         [ 1.2635]],

        ...,

        [[ 1.6823],
         [ 1.4213],
         [ 1.7449],
         ...,
         [-1.1047],
         [-1.2310],
         [-1.2116]],

        [[ 2.5837],
         [ 2.4837],
         [ 2.0784],
         ...,
         [-1.1517],
         [-1.2749],
         [-1.1968]],

        [[-1.5012],
         [-1.4436],
         [-1.6842],
         ...,
         [-0.2670],
         [-0.2209],
         [-0.4756]]], grad_fn=<PermuteBackward0>) tensor([[[ 1.8528],
         [ 1.5172],
         [ 0.8459],
         ...,
         [ 1.5172],
         [ 1.3494],
         [ 1.8528]],

      

tensor([[[-0.5585],
         [-0.4669],
         [-0.2426],
         ...,
         [-0.9863],
         [-0.9220],
         [-0.9802]],

        [[-0.5863],
         [-0.4265],
         [-0.4292],
         ...,
         [-1.2549],
         [-1.3431],
         [-1.2185]],

        [[ 2.5955],
         [ 2.7410],
         [ 2.6025],
         ...,
         [ 0.0596],
         [-0.0865],
         [-0.3726]],

        ...,

        [[-0.8758],
         [-0.7224],
         [-0.3517],
         ...,
         [-1.3446],
         [-1.3921],
         [-1.2329]],

        [[ 0.3205],
         [ 0.2511],
         [ 0.6671],
         ...,
         [-0.5337],
         [-0.4098],
         [-0.4413]],

        [[-1.7580],
         [-1.7622],
         [-1.7349],
         ...,
         [ 1.5265],
         [ 1.6457],
         [ 1.8424]]], grad_fn=<PermuteBackward0>) tensor([[[-0.9079],
         [-0.0779],
         [-0.4099],
         ...,
         [-0.9079],
         [-1.2399],
         [-1.5719]],

      

tensor([[[-0.2301],
         [-0.2090],
         [-0.1030],
         ...,
         [-1.1353],
         [-1.2067],
         [-1.1109]],

        [[ 1.4434],
         [ 1.4010],
         [ 1.6959],
         ...,
         [-0.7060],
         [-0.4474],
         [ 0.2783]],

        [[-1.1284],
         [-1.0815],
         [-0.9665],
         ...,
         [ 1.3668],
         [ 1.5579],
         [ 1.2647]],

        ...,

        [[ 0.4194],
         [ 0.4207],
         [ 0.6782],
         ...,
         [-1.4578],
         [-1.1195],
         [-1.7389]],

        [[-0.9673],
         [-0.9594],
         [-0.9385],
         ...,
         [ 1.1328],
         [ 0.9550],
         [ 1.2197]],

        [[-0.7935],
         [-0.8831],
         [-0.8778],
         ...,
         [ 1.2752],
         [ 1.1654],
         [ 1.2595]]], grad_fn=<PermuteBackward0>) tensor([[[-0.2701],
         [-0.2040],
         [-0.1269],
         ...,
         [-1.1077],
         [-1.2951],
         [-0.9424]],

      

tensor([[[ 1.3441],
         [ 1.2491],
         [ 1.4051],
         ...,
         [-0.7537],
         [-0.2399],
         [-0.1874]],

        [[ 1.4478],
         [ 1.4012],
         [ 1.5396],
         ...,
         [-0.2153],
         [-0.1494],
         [-0.0674]],

        [[-1.1813],
         [-0.8463],
         [-1.4112],
         ...,
         [-0.8015],
         [-0.7903],
         [-0.8431]],

        ...,

        [[ 1.5179],
         [ 0.6869],
         [-0.9958],
         ...,
         [-0.4901],
         [-0.1029],
         [-0.0892]],

        [[ 0.2028],
         [ 0.3113],
         [ 0.4322],
         ...,
         [-0.1906],
         [-0.2754],
         [-0.2653]],

        [[ 0.5003],
         [ 0.8490],
         [ 0.8305],
         ...,
         [ 0.1115],
         [ 0.0774],
         [-0.3794]]], grad_fn=<PermuteBackward0>) tensor([[[ 1.4346],
         [ 1.2602],
         [ 1.3959],
         ...,
         [-0.4066],
         [-0.1934],
         [ 1.0858]],

      

tensor([[[-1.0864],
         [-1.1061],
         [-1.0626],
         ...,
         [-0.8257],
         [-0.4407],
         [-0.3078]],

        [[ 0.5405],
         [ 0.7862],
         [ 0.8608],
         ...,
         [ 0.3311],
         [ 0.6856],
         [ 0.9798]],

        [[ 0.8346],
         [ 0.8461],
         [ 0.0460],
         ...,
         [-1.2375],
         [-1.1878],
         [-1.1832]],

        ...,

        [[-1.1499],
         [-1.4681],
         [-1.2420],
         ...,
         [-0.6006],
         [-0.8617],
         [-0.7799]],

        [[ 2.0325],
         [ 1.8012],
         [ 1.5302],
         ...,
         [ 0.2235],
         [ 0.4500],
         [ 0.4412]],

        [[-0.6446],
         [-0.5258],
         [-0.5049],
         ...,
         [-1.6538],
         [-1.8229],
         [-1.9250]]], grad_fn=<PermuteBackward0>) tensor([[[-1.0318],
         [-1.2356],
         [-1.4977],
         ...,
         [-1.0318],
         [-0.4202],
         [-0.5076]],

      

tensor([[[-0.9270],
         [-0.8710],
         [-0.8241],
         ...,
         [-1.5609],
         [-1.5064],
         [-1.5461]],

        [[ 0.3738],
         [ 0.3667],
         [ 0.6160],
         ...,
         [-0.2844],
         [-0.4954],
         [-0.2866]],

        [[-0.9277],
         [-0.8196],
         [-0.6439],
         ...,
         [ 1.7886],
         [ 1.7675],
         [ 2.0154]],

        ...,

        [[-0.3734],
         [-0.4208],
         [ 0.0944],
         ...,
         [-1.0677],
         [-1.1607],
         [-1.1629]],

        [[ 1.9374],
         [ 2.4245],
         [ 2.3047],
         ...,
         [ 0.5215],
         [ 0.4087],
         [ 0.3740]],

        [[-1.5259],
         [-1.5676],
         [-1.5874],
         ...,
         [ 0.7802],
         [ 0.9888],
         [ 0.6737]]], grad_fn=<PermuteBackward0>) tensor([[[-1.2691],
         [-1.0565],
         [-0.6881],
         ...,
         [-1.5964],
         [-1.5056],
         [-1.4893]],

      

tensor([[[ 1.4191],
         [ 1.7550],
         [ 1.5359],
         ...,
         [-1.1212],
         [-1.1051],
         [-0.8422]],

        [[ 1.4489],
         [ 1.8713],
         [ 1.7367],
         ...,
         [-0.7301],
         [-0.8641],
         [-0.7702]],

        [[-1.1779],
         [-1.1902],
         [-1.5636],
         ...,
         [ 0.5931],
         [ 0.5560],
         [ 0.5044]],

        ...,

        [[ 1.0915],
         [ 1.1047],
         [ 1.3437],
         ...,
         [-0.9863],
         [-0.5019],
         [-0.2632]],

        [[-0.4006],
         [-0.5919],
         [-0.3378],
         ...,
         [-1.0230],
         [-1.1944],
         [-1.2119]],

        [[-0.8522],
         [-0.8620],
         [-0.9084],
         ...,
         [ 0.6672],
         [ 0.5759],
         [ 0.4769]]], grad_fn=<PermuteBackward0>) tensor([[[ 1.5727],
         [ 1.6209],
         [ 1.8680],
         ...,
         [-0.9404],
         [-0.6089],
         [-0.6391]],

      

tensor([[[ 1.6580],
         [ 1.6292],
         [ 1.6971],
         ...,
         [-0.6962],
         [-0.7186],
         [-0.7112]],

        [[-0.3657],
         [-0.2993],
         [-0.2623],
         ...,
         [ 1.1536],
         [ 1.3272],
         [ 1.3864]],

        [[-1.2662],
         [-1.3689],
         [-1.6844],
         ...,
         [ 1.3505],
         [ 2.5326],
         [ 2.6445]],

        ...,

        [[ 0.7323],
         [ 0.6234],
         [ 0.0778],
         ...,
         [-1.5267],
         [-1.5065],
         [-1.6512]],

        [[-1.4441],
         [-1.7563],
         [-1.8467],
         ...,
         [-0.6728],
         [-0.8536],
         [-0.6774]],

        [[ 0.4949],
         [ 1.0384],
         [ 1.6186],
         ...,
         [-0.7800],
         [-0.5783],
         [-0.4890]]], grad_fn=<PermuteBackward0>) tensor([[[ 1.6808],
         [ 1.6234],
         [ 1.5009],
         ...,
         [-0.8802],
         [-0.7362],
         [-0.4272]],

      

tensor([[[ 2.3693],
         [ 2.2746],
         [ 1.9862],
         ...,
         [-1.4673],
         [-1.3533],
         [-1.2725]],

        [[-1.2127],
         [-1.0130],
         [-0.4057],
         ...,
         [-1.9964],
         [-2.1705],
         [-2.1356]],

        [[ 0.4582],
         [ 0.7170],
         [ 1.6179],
         ...,
         [-0.8314],
         [-0.9265],
         [-1.0106]],

        ...,

        [[ 0.8193],
         [ 0.7321],
         [ 0.5348],
         ...,
         [ 1.8896],
         [ 1.8692],
         [ 1.9200]],

        [[-1.5205],
         [-1.4365],
         [-1.6648],
         ...,
         [-0.3260],
         [-0.6193],
         [-0.6862]],

        [[-1.7109],
         [-1.7272],
         [-1.8024],
         ...,
         [ 0.6217],
         [ 0.5173],
         [ 0.3130]]], grad_fn=<PermuteBackward0>) tensor([[[ 2.7457],
         [ 2.2767],
         [ 2.0087],
         ...,
         [-1.1404],
         [-1.2074],
         [-1.1404]],

      

tensor([[[-1.3805],
         [-1.4187],
         [-1.1417],
         ...,
         [ 0.6795],
         [ 0.8716],
         [-0.2786]],

        [[-0.0275],
         [ 0.3650],
         [ 0.4750],
         ...,
         [-0.2830],
         [-0.2862],
         [-0.4812]],

        [[-1.0604],
         [-0.8737],
         [-0.9988],
         ...,
         [ 1.1332],
         [ 1.1150],
         [ 0.8237]],

        ...,

        [[-1.5774],
         [-1.3607],
         [-1.2704],
         ...,
         [ 1.6053],
         [ 1.4716],
         [ 1.5249]],

        [[-0.3886],
         [-0.2266],
         [-0.6348],
         ...,
         [-1.4230],
         [-1.4597],
         [-1.5574]],

        [[ 1.6640],
         [ 1.9465],
         [ 1.6254],
         ...,
         [-1.3377],
         [-1.0484],
         [-1.0297]]], grad_fn=<PermuteBackward0>) tensor([[[-1.7148],
         [-1.5404],
         [-0.9769],
         ...,
         [ 0.7891],
         [ 0.2004],
         [-1.3670]],

      

tensor([[[-1.3459],
         [-1.3094],
         [-1.2026],
         ...,
         [ 0.1149],
         [ 0.3031],
         [ 0.3700]],

        [[ 1.8672],
         [ 1.4374],
         [ 0.7390],
         ...,
         [-1.1527],
         [-1.2175],
         [-1.1057]],

        [[-0.7577],
         [-0.7603],
         [-0.8292],
         ...,
         [ 1.1015],
         [ 0.9974],
         [ 0.6988]],

        ...,

        [[-0.7871],
         [-1.0118],
         [-1.0975],
         ...,
         [ 2.3628],
         [ 1.9659],
         [ 1.7741]],

        [[-0.4151],
         [-0.3168],
         [-0.0848],
         ...,
         [-0.7997],
         [-0.9615],
         [-1.5498]],

        [[ 0.8849],
         [ 0.6959],
         [ 0.5467],
         ...,
         [-1.4379],
         [-1.5745],
         [-1.5813]]], grad_fn=<PermuteBackward0>) tensor([[[-1.3448],
         [-1.3254],
         [-1.1895],
         ...,
         [ 0.1357],
         [ 0.3347],
         [ 0.2037]],

      

tensor([[[-0.3697],
         [-0.5364],
         [-0.5890],
         ...,
         [-0.1833],
         [ 0.1081],
         [-0.3375]],

        [[-0.3573],
         [-0.4592],
         [-0.4660],
         ...,
         [ 0.2547],
         [ 0.1272],
         [ 0.0152]],

        [[-0.1853],
         [-0.0914],
         [ 0.3839],
         ...,
         [-0.8601],
         [-1.5966],
         [-1.4235]],

        ...,

        [[ 1.2583],
         [ 1.5755],
         [ 1.9003],
         ...,
         [-1.4738],
         [-1.6822],
         [-1.6465]],

        [[ 0.0882],
         [ 0.1476],
         [ 0.4469],
         ...,
         [ 1.5034],
         [ 1.7750],
         [ 1.6070]],

        [[-0.9052],
         [-0.8835],
         [-0.6756],
         ...,
         [-1.2025],
         [-1.0168],
         [-1.2808]]], grad_fn=<PermuteBackward0>) tensor([[[-0.0408],
         [-0.3283],
         [-0.5908],
         ...,
         [ 0.2717],
         [-0.0283],
         [-0.3033]],

      

tensor([[[-2.0168],
         [-2.0509],
         [-1.9054],
         ...,
         [ 1.1153],
         [ 0.9333],
         [ 0.2754]],

        [[ 1.7386],
         [ 1.6678],
         [ 1.6024],
         ...,
         [-0.8947],
         [-1.2748],
         [-1.2962]],

        [[-0.9326],
         [-1.1560],
         [-1.1262],
         ...,
         [ 0.6640],
         [ 0.7722],
         [ 0.6533]],

        ...,

        [[-0.4140],
         [-0.4229],
         [-0.4014],
         ...,
         [-0.1369],
         [ 0.2548],
         [ 0.2317]],

        [[ 1.2517],
         [ 1.4501],
         [ 1.4636],
         ...,
         [-0.7757],
         [-0.8754],
         [-0.8057]],

        [[-1.6458],
         [-1.7618],
         [-1.7728],
         ...,
         [ 0.8733],
         [ 0.8259],
         [ 0.8201]]], grad_fn=<PermuteBackward0>) tensor([[[-2.3195],
         [-2.3037],
         [-2.0821],
         ...,
         [ 1.2421],
         [ 0.8147],
         [ 0.3398]],

      

tensor([[[ 1.9352],
         [ 1.8647],
         [ 1.4176],
         ...,
         [ 1.2986],
         [ 1.1782],
         [ 1.2684]],

        [[ 1.4076],
         [ 1.3778],
         [ 0.7282],
         ...,
         [ 0.8681],
         [ 0.7372],
         [ 0.6441]],

        [[-1.1879],
         [-1.2053],
         [-1.3099],
         ...,
         [-0.3361],
         [-0.4341],
         [-0.4289]],

        ...,

        [[ 0.3567],
         [ 0.3509],
         [ 0.2918],
         ...,
         [-0.6540],
         [-0.6745],
         [-0.6813]],

        [[-1.2952],
         [-0.1915],
         [-0.3758],
         ...,
         [-0.5255],
         [-0.5388],
         [-0.3984]],

        [[ 0.1515],
         [ 0.1831],
         [ 0.1140],
         ...,
         [ 1.6788],
         [ 1.7982],
         [ 1.8375]]], grad_fn=<PermuteBackward0>) tensor([[[ 2.3166],
         [ 2.2398],
         [ 0.7854],
         ...,
         [ 1.5680],
         [ 1.0186],
         [ 0.2923]],

      

tensor([[[-0.2361],
         [-0.2736],
         [-0.2542],
         ...,
         [ 0.6426],
         [ 0.2762],
         [ 0.3565]],

        [[ 0.4166],
         [-0.3907],
         [-1.0380],
         ...,
         [ 0.9733],
         [ 0.9756],
         [ 1.1604]],

        [[ 1.7677],
         [ 2.2926],
         [ 2.2580],
         ...,
         [-1.1540],
         [-1.1880],
         [-1.1481]],

        ...,

        [[ 2.0234],
         [ 1.8413],
         [ 1.5440],
         ...,
         [ 0.4905],
         [ 0.4841],
         [ 0.2343]],

        [[-0.9217],
         [-1.1284],
         [-1.2389],
         ...,
         [ 0.5010],
         [ 0.3075],
         [ 0.3083]],

        [[-0.3605],
         [-0.4310],
         [-0.4226],
         ...,
         [ 1.3057],
         [ 0.9925],
         [ 0.9383]]], grad_fn=<PermuteBackward0>) tensor([[[-0.2875],
         [-0.3436],
         [-0.7084],
         ...,
         [ 0.8350],
         [ 0.3018],
         [ 0.3299]],

      

tensor([[[-1.4876],
         [-0.4917],
         [-0.2865],
         ...,
         [-1.1163],
         [-0.2907],
         [-0.5051]],

        [[ 1.7155],
         [ 0.9206],
         [-0.2294],
         ...,
         [ 1.2029],
         [ 1.2013],
         [ 1.2883]],

        [[ 1.4452],
         [ 1.2856],
         [ 1.1089],
         ...,
         [-1.2190],
         [-1.3059],
         [-1.4055]],

        ...,

        [[-1.0756],
         [-0.6300],
         [-0.8893],
         ...,
         [ 1.2477],
         [ 1.6631],
         [ 1.9162]],

        [[ 2.2044],
         [ 1.8167],
         [ 1.4531],
         ...,
         [-0.9802],
         [-0.6393],
         [-0.7671]],

        [[ 1.6850],
         [ 1.4544],
         [ 0.9663],
         ...,
         [-1.8909],
         [-2.4981],
         [-2.4407]]], grad_fn=<PermuteBackward0>) tensor([[[-1.7481],
         [-0.4171],
         [-0.5195],
         ...,
         [-1.1748],
         [-0.3352],
         [-0.2533]],

      

tensor([[[-0.9492],
         [-0.9089],
         [-0.9504],
         ...,
         [ 0.3014],
         [ 0.4354],
         [ 0.3538]],

        [[-0.1716],
         [-0.3041],
         [-0.3772],
         ...,
         [ 0.6356],
         [ 0.6437],
         [ 0.5882]],

        [[ 1.2336],
         [ 1.2344],
         [ 1.1363],
         ...,
         [-0.7443],
         [-0.6036],
         [-0.6768]],

        ...,

        [[-0.9662],
         [-0.4287],
         [-0.4054],
         ...,
         [ 1.0609],
         [ 0.7364],
         [ 0.9654]],

        [[-1.0967],
         [-1.0972],
         [-1.1903],
         ...,
         [ 0.9614],
         [ 1.1598],
         [ 1.4647]],

        [[ 2.2302],
         [ 1.9016],
         [ 1.7348],
         ...,
         [-1.5326],
         [-1.5688],
         [-1.4940]]], grad_fn=<PermuteBackward0>) tensor([[[-0.9346],
         [-0.9952],
         [-0.6317],
         ...,
         [ 0.3506],
         [ 0.4415],
         [ 0.2727]],

      

tensor([[[-0.5194],
         [-0.8467],
         [-0.8502],
         ...,
         [-0.2770],
         [-0.4079],
         [-0.9317]],

        [[-1.6201],
         [-1.6636],
         [-1.6548],
         ...,
         [-0.9224],
         [-1.0948],
         [-0.9649]],

        [[ 0.1978],
         [ 0.0491],
         [ 0.1117],
         ...,
         [ 2.1692],
         [ 2.0933],
         [ 2.1815]],

        ...,

        [[ 1.5789],
         [ 1.5405],
         [ 2.1261],
         ...,
         [-0.8853],
         [-0.8291],
         [-0.8598]],

        [[ 2.0091],
         [ 1.7088],
         [ 1.6460],
         ...,
         [-1.2267],
         [-1.2062],
         [-1.0065]],

        [[-1.9242],
         [-1.8996],
         [-1.6926],
         ...,
         [-0.8663],
         [-0.8227],
         [-0.9489]]], grad_fn=<PermuteBackward0>) tensor([[[-0.7736],
         [-1.1834],
         [-1.0026],
         ...,
         [-0.4120],
         [-1.8705],
         [-1.8343]],

      

tensor([[[-0.6303],
         [-0.5063],
         [-0.3668],
         ...,
         [ 2.4732],
         [ 2.2699],
         [ 1.7879]],

        [[ 0.4329],
         [ 1.2299],
         [ 2.3890],
         ...,
         [-0.6570],
         [-0.5189],
         [-0.4922]],

        [[ 0.6359],
         [ 0.4795],
         [ 0.5185],
         ...,
         [-1.2989],
         [-1.1249],
         [-1.1512]],

        ...,

        [[ 0.2868],
         [ 0.0796],
         [-0.5902],
         ...,
         [-1.5559],
         [-1.5535],
         [-1.5723]],

        [[ 1.1196],
         [ 1.3202],
         [ 1.1525],
         ...,
         [-0.3836],
         [-0.2357],
         [-0.1994]],

        [[ 1.3628],
         [ 1.3117],
         [ 1.2260],
         ...,
         [-1.1113],
         [-1.1522],
         [-1.1633]]], grad_fn=<PermuteBackward0>) tensor([[[-0.2101],
         [-0.4774],
         [-0.2101],
         ...,
         [ 2.4635],
         [ 2.1962],
         [ 1.1267]],

      

tensor([[[-0.8323],
         [-1.0143],
         [-1.1402],
         ...,
         [ 0.2344],
         [-1.1970],
         [-1.2713]],

        [[-1.3820],
         [-1.2164],
         [-1.1511],
         ...,
         [ 2.1100],
         [ 1.7343],
         [ 2.0827]],

        [[-1.2498],
         [-1.3304],
         [-1.2528],
         ...,
         [-1.0451],
         [-1.1480],
         [-0.9634]],

        ...,

        [[ 2.5120],
         [ 2.2805],
         [ 1.6669],
         ...,
         [-0.2753],
         [ 0.0292],
         [ 0.1495]],

        [[ 1.0736],
         [ 1.1245],
         [ 1.0851],
         ...,
         [-0.3170],
         [-0.3016],
         [-0.4251]],

        [[-0.1648],
         [-0.1887],
         [ 0.1837],
         ...,
         [-0.7576],
         [-0.9314],
         [-0.8722]]], grad_fn=<PermuteBackward0>) tensor([[[-0.8123],
         [-1.0045],
         [-0.9084],
         ...,
         [-1.6291],
         [-1.1727],
         [-0.9324]],

      

tensor([[[ 2.1844],
         [ 1.6175],
         [ 1.2468],
         ...,
         [-0.4442],
         [-0.4120],
         [-0.0884]],

        [[ 2.1484],
         [ 2.4053],
         [ 2.2955],
         ...,
         [-1.2140],
         [-1.2215],
         [-1.1848]],

        [[ 1.1576],
         [ 0.9439],
         [ 0.6832],
         ...,
         [-1.4464],
         [-0.8529],
         [-0.8387]],

        ...,

        [[ 0.8782],
         [ 1.4221],
         [ 1.0305],
         ...,
         [-0.8605],
         [-0.8489],
         [-0.8734]],

        [[ 1.8900],
         [ 1.7047],
         [ 1.1321],
         ...,
         [ 0.7861],
         [ 1.6807],
         [ 1.6406]],

        [[-2.1268],
         [-1.4823],
         [-1.4821],
         ...,
         [-0.1299],
         [-0.0708],
         [-0.1818]]], grad_fn=<PermuteBackward0>) tensor([[[ 1.7992],
         [ 1.1962],
         [ 1.0058],
         ...,
         [-0.4223],
         [-0.3905],
         [ 0.0855]],

      

tensor([[[-1.2357e+00],
         [-1.3814e+00],
         [-1.4266e+00],
         ...,
         [ 1.4113e+00],
         [ 1.5310e+00],
         [ 1.3556e+00]],

        [[-2.0437e-02],
         [ 5.0935e-01],
         [-4.0040e-02],
         ...,
         [ 8.9058e-01],
         [ 6.1407e-01],
         [ 7.2772e-01]],

        [[-1.5440e+00],
         [-1.5026e+00],
         [-1.3099e+00],
         ...,
         [ 6.5866e-04],
         [-1.5068e-01],
         [-2.1116e-01]],

        ...,

        [[ 1.8065e+00],
         [ 1.5349e+00],
         [ 1.3660e+00],
         ...,
         [-1.1736e+00],
         [-7.7770e-01],
         [-8.5592e-01]],

        [[-2.8102e-02],
         [-1.0565e-01],
         [ 2.2016e-02],
         ...,
         [-6.1736e-01],
         [-5.1674e-01],
         [-6.5226e-01]],

        [[ 1.0782e+00],
         [ 9.3616e-01],
         [ 7.6216e-01],
         ...,
         [-8.0504e-01],
         [-8.1135e-01],
         [-8.4684e-01]]], grad_fn=<PermuteBackward0>

In [31]:
# def predict(model,back_iter):
#     enVec_list = []
#     with torch.no_grad():
#         for X in back_iter:
#             inputs = X.to(device)
#             _,enVec = model(inputs)
#             enVec_list.append(enVec)
#     return enVec_list

In [32]:
# #define device
# def try_gpu(i=0):
#     """Return gpu(i) if exists, otherwise return cpu()."""
#     if torch.cuda.device_count() >= i + 1:
#         return torch.device(f'cuda:{i}')
#     return torch.device('cpu')
# device=try_gpu()

In [26]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Transformer(nn.Module):
    def __init__(self, input_size, d_model, d_ff, num_heads,env_size, num_layers,dropout_rate):
        super(Transformer, self).__init__()
        self.embedding = nn.Linear(input_size, d_model)
        self.encode = Encoder(d_model, d_ff, num_heads, num_layers,dropout_rate)
        self.linear1 = nn.Linear(d_model, env_size)
        self.rule = nn.ReLU()
        self.linear2 = nn.Linear(env_size,1)
        

    def forward(self, x):
        x = self.embedding(x)
#         print(x.shape)
        x = x.permute(1,0,2)
        encoded = self.encode(x)
        encoded = self.linear1(encoded)
        x = self.rule(encoded)
        x = self.linear2(x)
#         print(x.shape)
        decoded = x.permute(1,0,2)
        return decoded, encoded.permute(1,0,2)[0,-1,:]  


In [27]:
class Encoder(nn.Module):
    def __init__(self, d_model, d_ff, num_heads, num_layers,dropout_rate):
        super(Encoder, self).__init__()
        self.layers = nn.ModuleList([EncoderLayer(d_model, d_ff, num_heads,dropout_rate) for _ in range(num_layers)])

    def forward(self, x):
        for layer in self.layers:
            x = layer(x)
        return x

In [28]:
class EncoderLayer(nn.Module):
    def __init__(self, d_model, d_ff, num_heads,dropout_rate):
        super(EncoderLayer, self).__init__()
        self.self_attention = nn.MultiheadAttention(d_model, num_heads)
        self.dropout1 = nn.Dropout(dropout_rate)
        self.feed_forward = FeedForward(d_model, d_ff)
        self.dropout2 = nn.Dropout(dropout_rate)
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)

    def forward(self, x):
        residual = x  # 保存输入的残差连接

        # Self-Attention
        x, _ = self.self_attention(x, x, x)
        x = self.dropout1(x)
        x = x + residual  # 残差连接
        x = self.norm1(x)  # Add & Norm

        residual = x  # 保存 Self-Attention 后的残差连接

        # Feed-Forward
        x = self.feed_forward(x)
        x = self.dropout2(x)
        x = x + residual  # 残差连接
        x = self.norm2(x)  # Add & Norm

        return x

In [29]:
class FeedForward(nn.Module):
    def __init__(self, d_model, d_ff):
        super(FeedForward, self).__init__()
        self.linear1 = nn.Linear(d_model, d_ff)
        self.linear2 = nn.Linear(d_ff, d_model)

    def forward(self, x):
        x = F.relu(self.linear1(x))
        x = self.linear2(x)
        return x

In [ ]:
#模型训练
def train(model, train_iter, optimizer, num_epochs): 
    # 训练循环
    for epoch in range(num_epochs):
        model.train()
        total_loss = 0.0
        enVec_list = []
        for X, y, z, zp in train_iter:  
            optimizer.zero_grad()

            inputs = X.to(device)
            targets = y.unsqueeze(2).to(device)
            pred,enVec = model(inputs,targets)
            enVec_list.append(enVec)
#             print(pred,targets)
            loss = nn.MSELoss()(pred, targets)  
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        # 打印每个 epoch 的损失
        print(f"Epoch {epoch+1}: Loss: {total_loss/len(train_iter):.4f}")
    return enVec_list
# 模型评估
def val(model, val_iter):
    model.eval()
    total_loss = 0.0
    enVec_list = []
    with torch.no_grad():
        for X, y, z, zp in val_iter: 
            inputs = X.to(device)
            targets = y.unsqueeze(2).to(device)
            pred, enVec = model(inputs,targets)
            enVec_list.append(enVec)
            loss = nn.MSELoss()(pred, targets)  
            total_loss += loss.item()
    print(f"val Loss: {total_loss/len(val_iter):.4f}")
    return enVec_list

In [ ]:
def predict(model,back_iter):
    enVec_list = []
    with torch.no_grad():
        for X in back_iter:
            inputs = X.to(device)
            _,enVec = model(inputs)
            enVec_list.append(enVec)
    return enVec_list

In [ ]:
#define device
def try_gpu(i=0):
    """Return gpu(i) if exists, otherwise return cpu()."""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')
device=try_gpu()

In [ ]:
# 定义模型
model = Transformer(input_size = 42, d_model = 128 , num_layers = 2, num_heads = 8,env_size =40,dropout_rate=0.2)
optimizer = optim.Adam(model.parameters(), lr=0.001)
outcoming =train(model,train_iter,optimizer,5)
valtest =val(model,val_iter)

# Part 4: Preprocess Data
Data preprocessing is a crucial step for training a high quality machine learning model. We need to check for missing data and do feature engineering in order to convert the data into a model-ready state.
* Add technical indicators. In practical trading, various information needs to be taken into account, for example the historical stock prices, current holding shares, technical indicators, etc. In this article, we demonstrate two trend-following technical indicators: MACD and RSI.
* Add turbulence index. Risk-aversion reflects whether an investor will choose to preserve the capital. It also influences one's trading strategy when facing different market volatility level. To control the risk in a worst-case scenario, such as financial crisis of 2007–2008, FinRL employs the financial turbulence index that measures extreme asset price fluctuation.

In [ ]:
# feature_enginner
alltic_list = [i for i in range(k)]

def Feature_enginner(model, processed_df, full_list, alltic_list, batch_size=64, k=20, env_size=40,dela = 48):
    back_iter = DataLoader(StockDataset_back([i for i in range(k)],full_list), shuffle=False, batch_size=batch_size, num_workers=0,drop_last=False)
    
    new_state = predict(model,back_iter)
    concatenated_tensor = torch.cat(new_state, dim=0)
    concatenated_tensor = concatenated_tensor.view(-1,env_size)
    feature_df = pd.DataFrame(concatenated_tensor.numpy())
    
    full_delay_df = delaydate(dela ,processed_df)
    
    merged_df = pd.concat([full_delay_df, feature_df], axis=1)
    merged_df = merged_df.loc[:,['tic','date','close'] + INDICATORS + [i for i in range(env_size)]]
    merged_df.columns = ['tic','date','close'] + INDICATORS + [f"temporal_feature_{i}" for i in range(env_size)]
    return merged_df

In [ ]:
addfeature_df = Feature_enginner(model, processed_df3, array_full_list, alltic_list, batch_size=64, k=20 ,env_size=40, dela=48)

In [ ]:
addfeature_df.to_csv('74addfeature_df.csv',index=None)

In [ ]:
addfeature_df = pd.read_csv('74addfeature_df.csv')

In [ ]:
addfeature_df['date'] = pd.to_datetime(addfeature_df['date'])

In [ ]:
processed_df3.to_csv('74_processed_best.csv',index=None)

In [ ]:
processed_df3 = pd.read_csv('74_processed_best.csv')

In [ ]:
processed_df3['date'] = pd.to_datetime(processed_df3['date'])

In [ ]:
addfeature_df = fe.add_turbulence(addfeature_df)
addfeature_df = addfeature_df.fillna(method="ffill").fillna(method="bfill")

In [ ]:
import datetime
processed['date'] = pd.to_datetime(processed['date'],format='%Y%m%d')
processed

In [ ]:
list_ticker = processed["tic"].unique().tolist()
# list_date = list(pd.date_range(processed['date'].min(),processed['date'].max()).astype(str))
# combination = list(itertools.product(list_date,list_ticker))

# processed_full = pd.DataFrame(combination,columns=["date","tic"]).merge(processed,on=["date","tic"],how="left")
# processed_full = processed_full[processed_full['date'].isin(processed['date'])]
# processed_full = processed_full.sort_values(['date','tic'])

processed_full = processed

<a id='4'></a>
# Part 5. Design Environment
Considering the stochastic and interactive nature of the automated stock trading tasks, a financial task is modeled as a **Markov Decision Process (MDP)** problem. The training process involves observing stock price change, taking an action and reward's calculation to have the agent adjusting its strategy accordingly. By interacting with the environment, the trading agent will derive a trading strategy with the maximized rewards as time proceeds.

Our trading environments, based on OpenAI Gym framework, simulate live stock markets with real market data according to the principle of time-driven simulation.

The action space describes the allowed actions that the agent interacts with the environment. Normally, action a includes three actions: {-1, 0, 1}, where -1, 0, 1 represent selling, holding, and buying one share. Also, an action can be carried upon multiple shares. We use an action space {-k,…,-1, 0, 1, …, k}, where k denotes the number of shares to buy and -k denotes the number of shares to sell. For example, "Buy 10 shares of AAPL" or "Sell 10 shares of AAPL" are 10 or -10, respectively. The continuous action space needs to be normalized to [-1, 1], since the policy is defined on a Gaussian distribution, which needs to be normalized and symmetric.

In [ ]:
selfattn_indicator_list = [f"temporal_feature_{i}" for i in range(40)]

In [ ]:
selected_tics = addfeature_df.tic.unique()
selected_tics

In [ ]:
TRAIN_START_DATE = addfeature_df['date'].unique()[0]

In [ ]:
TRAIN_START_DATE

In [ ]:
stock_dimension = 20
state_space = 1 + 2*stock_dimension + len(INDICATORS)*stock_dimension + len(selfattn_indicator_list)*stock_dimension
print(f"Stock Dimension: {stock_dimension}, State Space: {state_space}")

In [ ]:
stock_dimension = len(processed_df3.tic.unique())
state_space = 1 + 2*stock_dimension + len(INDICATORS)*stock_dimension
print(f"Stock Dimension: {stock_dimension}, State Space: {state_space}")


In [ ]:
env_kwargs = {
    "hmax": 100, 
    "initial_amount": 1000000, 
    "buy_cost_pct": 0.001, 
    "sell_cost_pct": 0.001, 
    "state_space": state_space, 
    "stock_dim": stock_dimension, 
    "tech_indicator_list": INDICATORS,
    "action_space": stock_dimension, 
    "reward_scaling": 1e-4,
    "print_verbosity":5
    
}

<a id='5'></a>
# Part 6: Implement DRL Algorithms
* The implementation of the DRL algorithms are based on **OpenAI Baselines** and **Stable Baselines**. Stable Baselines is a fork of OpenAI Baselines, with a major structural refactoring, and code cleanups.
* FinRL library includes fine-tuned standard DRL algorithms, such as DQN, DDPG,
Multi-Agent DDPG, PPO, SAC, A2C and TD3. We also allow users to
design their own DRL algorithms by adapting these DRL algorithms.

* In this notebook, we are training and validating 3 agents (A2C, PPO, DDPG) using Rolling-window Ensemble Method ([reference code](https://github.com/AI4Finance-LLC/Deep-Reinforcement-Learning-for-Automated-Stock-Trading-Ensemble-Strategy-ICAIF-2020/blob/80415db8fa7b2179df6bd7e81ce4fe8dbf913806/model/models.py#L92))

In [ ]:
rebalance_window = 63 # rebalance_window is the number of days to retrain the model
validation_window = 63 # validation_window is the number of days to do validation and trading (e.g. if validation_window=63, then both validation and trading period will be 63 days)

ensemble_agent = DRLEnsembleAgent(df=processed_df3,
                 train_period=(TRAIN_START_DATE,TRAIN_END_DATE),
                 val_test_period=(TRADE_START_DATE,TRADE_END_DATE),
                 rebalance_window=rebalance_window, 
                 validation_window=validation_window, 
#                  attn_indicator_list = selfattn_indicator_list,                 
                 **env_kwargs)



In [ ]:
TRADE_END_DATE

In [ ]:
SAC_model_kwargs = {
    "batch_size": 128,
    "buffer_size": 100000,
    "learning_rate": 0.0001,
    "learning_starts": 100,
    "ent_coef": "auto_0.1",
                }

PPO_model_kwargs = {
    "ent_coef":0.01,
    "n_steps": 2048,
    "learning_rate": 0.00025,
    "batch_size": 128
                    }

TD3_model_kwargs = {
    "batch_size": 128, 
    "buffer_size": 1000000, 
    "learning_rate": 0.001
                }

timesteps_dict = {'sac' : 10000, 
                 'ppo' : 10000, 
                 'td3' : 10000
                 }

In [ ]:
import torch
device = torch.device("mps")

In [ ]:
df_summary = ensemble_agent.run_ensemble_strategy_com(SAC_model_kwargs,
                                                 PPO_model_kwargs,
                                                 TD3_model_kwargs,
                                                 timesteps_dict)

In [ ]:
df_summary

<a id='6'></a>
# Part 7: Backtest Our Strategy
Backtesting plays a key role in evaluating the performance of a trading strategy. Automated backtesting tool is preferred because it reduces the human error. We usually use the Quantopian pyfolio package to backtest our trading strategies. It is easy to use and consists of various individual plots that provide a comprehensive image of the performance of a trading strategy.

In [ ]:
unique_trade_date = addfeature_df[(addfeature_df.date > TRADE_START_DATE)&(addfeature_df.date <= TRADE_END_DATE)].date.unique()

In [ ]:
df_trade_date = pd.DataFrame({'datadate':unique_trade_date})

df_account_value=pd.DataFrame()
for i in range(rebalance_window+validation_window, len(unique_trade_date)+1,rebalance_window):
    temp = pd.read_csv('results/account_value_trade_{}_{}.csv'.format('ensemble',i))
    df_account_value = df_account_value.append(temp,ignore_index=True)
sharpe=(252**0.5)*df_account_value.account_value.pct_change(1).mean()/df_account_value.account_value.pct_change(1).std()
print('Sharpe Ratio: ',sharpe)
df_account_value=df_account_value.join(df_trade_date[validation_window:].reset_index(drop=True))

In [ ]:
df_account_value

In [ ]:
%matplotlib inline
df_account_value.account_value.plot()

<a id='6.1'></a>
## 7.1 BackTestStats
pass in df_account_value, this information is stored in env class


In [ ]:
print("==============Get Backtest Results===========")
#now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')

perf_stats_all = backtest_stats(account_value=df_account_value)
perf_stats_all = pd.DataFrame(perf_stats_all)
#perf_stats_all.to_csv("./"+RESULTS_DIR+"/perf_stats_all_"+now+'.csv')

In [ ]:
print("==============Get Backtest Results===========")
#now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')

perf_stats_all = backtest_stats(account_value=df_account_value)
perf_stats_all = pd.DataFrame(perf_stats_all)
#perf_stats_all.to_csv("./"+RESULTS_DIR+"/perf_stats_all_"+now+'.csv')

In [ ]:
selected_tics = addfeature_df['tic'].unique()

In [ ]:
#获取随机选择的tic在select_date的权重并修正
def get_selected_index_weight(df_index,select_date,selected_tics):
    df = df_index[df_index['trade_date'] == select_date]
    select_df = df[df['con_code'].isin(selected_tics)]
    select_df = select_df.drop('index_code',axis=1).rename(columns={'con_code':'tic','trade_date':'date'})
    select_df = select_df.reset_index()
    weight_sum = select_df['weight'].sum()
#     print(select_df)
    for i in range(len(select_df)):
        select_df.loc[i,'weight'] = (select_df.loc[i,'weight'] / weight_sum)*100
    return select_df.loc[:,['tic','date','weight']]

baseline_weight =get_selected_index_weight(df_index,select_date,selected_tics)
baseline_weight = baseline_weight.sort_values(['tic'],ascending=True).reset_index(drop=True)
print(baseline_weight)

In [ ]:
#计算所选股票的buy & hold策略
def calculate_selected_baseline(df,full_date_range,selected_tics):
    df = df.sort_values(['tic','date'],ascending=True).reset_index(drop=True)
    baseline = pd.DataFrame({'date':full_date_range['date']})
    for i in range(len(full_date_range)):
        temp_date = full_date_range.loc[i,'date']
        temp_df = df[df['date'] == temp_date].sort_values('tic',ascending=True)
        close = list(temp_df['close'])
        weight = list(baseline_weight['weight'])
        baseline.loc[i,'account_value'] = sum(np.array(close) * np.array(weight)) #注意权重和收盘价对应的股票顺序
    baseline['date'] = pd.to_datetime(baseline['date'])
#     baseline.set_index("date", inplace=True, drop=True)
#     baseline.index = baseline.index.tz_localize("UTC")
    return baseline
# full_date_range = get_trading_days(exchange='SSE',start_date='20210301', end_date='20230227')
# full_date_range = full_date_range.sort_values('trade_date',ascending=True).reset_index(drop=True)
full_date_range1 = pd.DataFrame({'date':df_account_value['date'].unique()}).reset_index(drop=True)
baseline_sse = calculate_selected_baseline(addfeature_df,full_date_range1,selected_tics)
baseline_sse

In [ ]:
merged_df

In [ ]:
#baseline stats
print("==============Get Baseline Stats===========")
# baseline_df = get_baseline(
#         ticker="^DJI", 
#         start = df_account_value.loc[0,'date'],
#         end = df_account_value.loc[len(df_account_value)-1,'date'])

stats = backtest_stats(baseline_sse, value_col_name = 'account_value')

<a id='6.2'></a>
## 7.2 BackTestPlot

In [ ]:
import pyfolio
from copy import deepcopy
def backtest_plot_com(
    account_value,
    baseline,
    baseline_start=TRADE_START_DATE,
    baseline_end=TRADE_END_DATE,
    value_col_name="account_value",
):
    df = deepcopy(account_value)
    df["date"] = pd.to_datetime(df["date"])
    test_returns = get_daily_return(df, value_col_name=value_col_name)
#     pro = ts.pro_api()
#     baseline_df = pro.index_daily(ts_code='000016.sh',start_date = '20200301',end_date='20230227')
#     baseline_df = baseline_df.rename(columns={'trade_date':'date'})
#     baseline_df = baseline_df.sort_values('date',ascending=True)
    baseline_returns = get_daily_return(baseline, value_col_name=value_col_name)
    with pyfolio.plotting.plotting_context(font_scale=1.1):
        pyfolio.create_full_tear_sheet(
            returns=test_returns, benchmark_rets=baseline_returns, set_context=False
        )

In [ ]:
print("==============Compare to SSE50===========")
# from finrl.plot import backtest_plot_com
%matplotlib inline
# S&P 500: ^GSPC
# Dow Jones Index: ^DJI
# NASDAQ 100: ^NDX
backtest_plot_com(account_value = df_account_value, 
                  baseline = baseline_sse,
                  baseline_start = df_account_value.loc[len(df_account_value)-1,'date'],
                  baseline_end = df_account_value.loc[0,'date']
                     )

In [ ]:
print("==============Compare to SSE50===========")
# from finrl.plot import backtest_plot_com
%matplotlib inline
# S&P 500: ^GSPC
# Dow Jones Index: ^DJI
# NASDAQ 100: ^NDX
backtest_plot_com(account_value = df_account_value, 
                  baseline = baseline_sse,
                  baseline_start = df_account_value.loc[len(df_account_value)-1,'date'],
                  baseline_end = df_account_value.loc[0,'date']
                     )